### ISSUE TITLE
Add Support for [RFC 6750] Bearer Token Usage (a.k.a. Opaque Tokens)

### ISSUE THREAD

**Issue by dfcoffin** [spring-projects/spring-authorization-server#100]
**Expected Behavior**

**Current Behavior**

**Context**

**Comment by jgrandja** [comment]
@dfcoffin The purpose of the Bearer Token Usage RFC 6750 is to specify how a client can use a bearer token when requesting a protected resource. The 3 options are header, form parameter and query parameter. The bearer token can be either opaque or self-contained (JWT). This spec is specific to the client.

The Token Introspection RFC 7662, specifies how a protected resource can introspect an opaque access token to determine the claims associated with the opaque access token in order to make an authorization decision. The authorization server will grant an opaque access token to the client and then the client will call the resource server, which in turn will call the authorization server's introspection endpoint to return the claims associated with the access token and apply the authorization. So the bottom line is that #52 will deliver opaque token support.

Hope all this makes sense?

**Comment by dfcoffin** [comment]
Does Release 0.0.1 support the generation of JWT and Opaque Tokens? If not what currently listed tasks will produce an opaque access token?
