### ISSUE TITLE
On the user consent page, clicking the cancel button produces a 500 error code

### ISSUE THREAD

**Issue by kuschzzp** [spring-projects/spring-authorization-server#1006]
**Describe the bug**
In the project example, click Cancel on the user consent page, return to the previous page, and click the `authorization code`  button again, reporting error code 500. 

`message-client` error message：
```
org.springframework.web.reactive.function.client.WebClientResponseException$Forbidden: 403 Forbidden from GET http://127.0.0.1:8090/messages
	at org.springframework.web.reactive.function.client.WebClientResponseException.create(WebClientResponseException.java:313) ~[spring-webflux-6.0.0-RC4.jar:6.0.0-RC4]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	*__checkpoint ⇢ 403 FORBIDDEN from GET http://127.0.0.1:8090/messages [DefaultWebClient]
Original Stack Trace:
		at org.springframework.web.reactive.function.client.WebClientResponseException.create(WebClientResponseException.java:313) ~[spring-webflux-6.0.0-RC4.jar:6.0.0-RC4]
		at org.springframework.web.reactive.function.client.DefaultClientResponse.lambda$createException$1(DefaultClientResponse.java:213) ~[spring-webflux-6.0.0-RC4.jar:6.0.0-RC4]
		at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:106) ~[reactor-core-3.5.0.jar:3.5.0]
```

**Expected behavior**
When the user clicks the cancel button it should return to the authorization page without the 500 error code. The user can then reselect the `Authorization Code` or `Client Credentials`.

**To Reproduce**
When i use the `custom-consent-authorizationserver` example, i can solve this problem by updating the  `consent.html` 
from `onclick="cancelConsent();` to `onclick="javascript:history.back(-1);"`.
```
.................
  <button class="btn btn-link regular" type="button" id="cancel-consent" onclick="javascript:history.back(-1);">
                          Cancel
  </button>
 .................
```

But when users don't want to customize the page, it's not clear how to solve the problem.

**Comment by jgrandja** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces this issue if you feel this is a genuine bug.

The sample is working as expected. Place a breakout in [AuthorizationController.authorizationCodeGrant()](https://github.com/spring-projects/spring-authorization-server/blob/main/samples/messages-client/src/main/java/sample/web/AuthorizationController.java#L54) and then inspect the JWT claims via `authorizedClient.getAccessToken().getTokenValue()` and you will see the claims:

```json
{
  "sub": "user1",
  "aud": "messaging-client",
  "nbf": 1671124666,
  "iss": "http://localhost:9000",
  "exp": 1671124966,
  "iat": 1671124666
}
```

Notice there is no `scope` claim because of the canceling of the authorization consent.

The access token is then passed to the resource server and triggers the 403 error.
