### ISSUE TITLE
Make .well-known path more flexible

### ISSUE THREAD

**Issue by everflux** [spring-projects/spring-authorization-server#1021]
**Expected Behavior**
Provide property to configure the path to the .well-known mapping

**Current Behavior**
Path is hardcoded as /.well-known/

**Context**
It would be great, if the location of the metadata could be configured.
I am aware that the "/.well-known" path is indeed named that way for a reason. I have a scenario where I need to decide to either change the servlet context-path or use a reverse proxy to work around the currently hardcoded metadata location in OAuth2AuthorizationServerMetadataEndpointFilter, OidcProviderConfigurationEndpointFilter and OAuth2AuthorizationServerConfigurer

**Comment by Chr3is** [comment]
As per specification:
"Authorization servers supporting metadata MUST make a JSON document containing metadata as specified in [Section 2](https://www.rfc-editor.org/rfc/rfc8414.html#section-2) available at a path formed by **inserting a well-known URI string into the authorization server's issuer identifier between the host component and the path component, if any.**


OAuth2: https://www.rfc-editor.org/rfc/rfc8414.html#section-3
OIDC: https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfig

For OIDC it MUST be`/.well-known/openid-configuration`
However for OAuth2 it would be valid to use something like that: `/.well-known/example-configuration` instead of `/.well-known/oauth-authorization-server`

**Comment by jgrandja** [comment]
@everflux As you are aware and as mentioned by @Chr3is, the language used in both the OIDC and OAuth2 specs are **MUST** as far as usage of `.well-known` defined by [RFC 5785](https://www.rfc-editor.org/rfc/rfc5785). Both specs state this as a requirement and do not leave any room for customization. Based on this, I'm going to close this as our goal is to comply with the specs.

However, you can  implement a `Filter` similar to `OidcProviderConfigurationEndpointFilter` and register it before `OidcProviderConfigurationEndpointFilter` using `HttpSecurity.addFilterBefore()`. The logic in `OidcProviderConfigurationEndpointFilter.doFilterInternal()` is quite minimal to copy so I think this would be an alternative option you may consider.

**Comment by everflux** [comment]
Thanks for looking into it and providing a possible alternative to implementing this.
