### ISSUE TITLE
Spring Authorization server - limit a client to a specific resource server

### ISSUE THREAD

**Issue by zxiaozhou** [spring-projects/spring-authorization-server#1033]
**Expected Behavior**

@Override
public void configure(ClientDetailsServiceConfigurer clients) throws Exception {
    ClientDetailsServiceBuilder.ClientBuilder clientBuilder = clients
        .inMemory()
        .withClient("client1")
        .resourceIds("resourceServer1")
        ...

**Context**

1. How to configure a resource id for a resource server
2. Client management How to store the resource ids authorized by the current client id(The old authorization management had this field)
<img width="548" alt="image" src="https://user-images.githubusercontent.com/62740686/210335540-161b73a7-f282-44d2-9a30-6d48e1e6b00e.png">

**Comment by jgrandja** [comment]
@zxiaozhou Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it).

Please see [OAuth2TokenCustomizer](https://docs.spring.io/spring-authorization-server/docs/current/reference/html/core-model-components.html#oauth2-token-customizer) as it allows you to add custom claims in the `Jwt`, e.g. `resource_id`.

You can store the `resource_id`'s for each client in `RegisteredClient.clientSettings`.

**Comment by jgrandja** [comment]
Related gh-279
