### ISSUE TITLE
Reuse token when certain factors are met

### ISSUE THREAD

**Issue by wapkch** [spring-projects/spring-authorization-server#1034]
**Expected Behavior**

It'll be nice if access token could be reuse when certain factors are met. Like the AuthenticationKeyGenerator in Spring Security OAuth.

When creating OAuth2AccessToken, find access token by key generated by AuthenticationKeyGenerator first(Maybe user ID, session ID or any others):
```
public class DefaultTokenServices implements AuthorizationServerTokenServices, ResourceServerTokenServices,
		ConsumerTokenServices, InitializingBean {

	@Transactional
	public OAuth2AccessToken createAccessToken(OAuth2Authentication authentication) throws AuthenticationException {

		OAuth2AccessToken existingAccessToken = tokenStore.getAccessToken(authentication);
		OAuth2RefreshToken refreshToken = null;
		if (existingAccessToken != null) {
			if (existingAccessToken.isExpired()) {
				if (existingAccessToken.getRefreshToken() != null) {
					refreshToken = existingAccessToken.getRefreshToken();
					// The token store could remove the refresh token when the
					// access token is removed, but we want to
					// be sure...
					tokenStore.removeRefreshToken(refreshToken);
				}
				tokenStore.removeAccessToken(existingAccessToken);
			}
			else {
				// Re-store the access token in case the authentication has changed
				tokenStore.storeAccessToken(existingAccessToken, authentication);
				return existingAccessToken;
			}
		}

           // ...
   }
}

public class InMemoryTokenStore implements TokenStore {

    public OAuth2AccessToken getAccessToken(OAuth2Authentication authentication) {
		String key = authenticationKeyGenerator.extractKey(authentication);
		OAuth2AccessToken accessToken = authenticationToAccessTokenStore.get(key);
		if (accessToken != null
				&& !key.equals(authenticationKeyGenerator.extractKey(readAuthentication(accessToken.getValue())))) {
			// Keep the stores consistent (maybe the same user is represented by this authentication but the details
			// have changed)
			storeAccessToken(accessToken, authentication);
		}
		return accessToken;
	}

}
```

**Current Behavior**

Every time we get token using authorization code, a new access token is issued, regardless of whether it is the same user and the same browser. 
Because OAuth2Authorization ID is a UUID and can not be easily replaced.
```
public OAuth2Authorization build() {
			Assert.hasText(this.principalName, "principalName cannot be empty");
			Assert.notNull(this.authorizationGrantType, "authorizationGrantType cannot be null");

			OAuth2Authorization authorization = new OAuth2Authorization();
			if (!StringUtils.hasText(this.id)) {
				this.id = UUID.randomUUID().toString();
			}
}
```

**Context**

In some cases, we need to get all tokens issued to a user. For example, in a concurrent session scenario, we want to kick out a user's non-latest sessions and tokens, we need to get the tokens issued to the user and do revocations. And i think the same is true in a single sign-out scenario.

**Comment by jgrandja** [comment]
@wapkch 

> Every time we get token using authorization code, a new access token is issued, regardless of whether it is the same user and the same browser.

Each time a client performs an `authorization_grant`, a new instance of `OAuth2Authorization` is created. This is the expected behaviour. Please see the [OAuth2Authorization](https://docs.spring.io/spring-authorization-server/docs/current/reference/html/core-model-components.html#oauth2-authorization) reference documentation for further details.

> In some cases, we need to get all tokens issued to a user.

You can extend `OAuth2AuthorizationService` and provide additional operations required by your application, for example:

```java
public interface CustomOAuth2AuthorizationService extends OAuth2AuthorizationService {

	List<OAuth2Authorization> findByPrincipalName(String principalName);

}
```

You would implement `CustomOAuth2AuthorizationService` and then register it as a `@Bean`. Then you can inject the bean and use `findByPrincipalName()` to perform the custom logic you require.

I'm going to close this as a new `OAuth2Authorization` per `authorization_grant` is works as designed and the custom operation/logic for `findByPrincipalName()` needs to be implemented in the consuming application.
