### ISSUE TITLE
Password Less authorisation and authentication using OTP 

### ISSUE THREAD

**Issue by riki-nitdgp** [spring-projects/spring-authorization-server#1042]
**Expected Behavior**
 I want to implement OTP (one-time password) based authorization and authentication using the Spring authorization server. How can we implement this

**Current Behavior**
 Currently, a Password and username are mandatory.

**Comment by mrFlick72** [comment]
Hi, @riki-nitdgp if you are interested I implemented MFA with OTP sent via mail in this open-source product that I led.

[VAuthenticatot](https://github.com/VAuthenticator) in particular here there is the [MFA package](https://github.com/VAuthenticator/vauthenticator/tree/master/src/main/kotlin/com/vauthenticator/server/mfa)

it is MFA not passwordless but if you are interested to some OTP details you can take inspiration if you want

**Comment by jgrandja** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it).

Related gh-534
