### ISSUE TITLE
if the authorization-server is behind of a gateway, the 302 redirect can not go to a correct uri.

### ISSUE THREAD

**Issue by wilsonlv** [spring-projects/spring-authorization-server#1043]
i got a problem by in this situation.

if the authorization-server is behind of a gateway, the 302 redirect can not go to a correct uri.
for example, the gateway server address is 127.0.0.1 and the authorization-server is 127.0.0.1:8888, i configured a consentPage '/oauth2/consent', then the 302 redirect url is 127.0.0.1:8888/oauth2/consent, this will result in a cross-domain request, so how can we resolve it

**Comment by jgrandja** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces this issue if you feel this is a genuine bug.

**Comment by poo0054** [comment]
My gateway IP is 8085. The server authorization server is 9000. Every time I use 127.0.0.1:8085 to access, it will jump to http://192.168.0.98:9000/login. Is there any parameter I can set for the base path of the server, or where can I go to find the answer. Thanks

**Comment by wilsonlv** [comment]
> My gateway IP is 8085. The server authorization server is 9000. Every time I use 127.0.0.1:8085 to access, it will jump to http://192.168.0.98:9000/login. Is there any parameter I can set for the base path of the server, or where can I go to find the answer. Thanks

try to add PreserveHostHeader to the application.yml of gateway
