### ISSUE TITLE
Why are entity properties not defined as protected?

### ISSUE THREAD

**Issue by malvandi** [spring-projects/spring-authorization-server#1071]
https://github.com/spring-projects/spring-authorization-server/blob/f0530e7433b1da385b390b6a3db8e1c0be57a3df/oauth2-authorization-server/src/main/java/org/springframework/security/oauth2/server/authorization/client/RegisteredClient.java#L46

Why are properties not defined as protected? Maybe someone wants to override some properties.

@jgrandja @anoopgarlapati

**Comment by Sm0keySa1m0n** [comment]
You have to override the getters, it's a bit annoying (_I think it should really be an interface_).

**Comment by sjohnr** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/questions/tagged/spring-security). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces this issue if you feel this is a genuine bug.

**Comment by jgrandja** [comment]
@malvandi See this [comment](https://github.com/spring-projects/spring-authorization-server/issues/80#issuecomment-626437872) for further details.
