### ISSUE TITLE
999 error

### ISSUE THREAD

**Issue by litaipo** [spring-projects/spring-authorization-server#1110]
**Describe the bug**
I encountered a major exception when running the sample code like this
![image](https://user-images.githubusercontent.com/20733031/222402278-958f987c-563e-4ef0-b023-9c00c558235a.png)

**To Reproduce**
1.
http://127.0.0.1:8080/oauth2/authorize?response_type=code&client_id=messaging-client&redirect_uri=http://baidu.com&state=somestate&scope=openid
2. login

**Comment by sjohnr** [comment]
@litaipo, thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/questions/tagged/spring-security). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces this issue if you feel this is a genuine bug.
