### ISSUE TITLE
About the token is still available after logout

### ISSUE THREAD

**Issue by IwantDomore** [spring-projects/spring-authorization-server#1115]
**Expected Behavior**
I think the old token should be disabled after logout

**Current Behavior**
After logout , I use the **old token** to access the resource server, and I can still get the resource 

**Context**
This problem has troubled me all morning，I hope you all can help me, thanks a lot

**Comment by sjohnr** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/questions/tagged/spring-security). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces this issue if you feel this is a genuine bug.

You may find the latest milestone release [1.1.0-M1](https://github.com/spring-projects/spring-authorization-server/releases/tag/1.1.0-M1) of interest, as it contains a preview of "OpenID Connect 1.0 Logout Endpoint", which we will [continue enhancing](https://github.com/spring-projects/spring-authorization-server/issues/1077) (including reference documentation).
