### ISSUE TITLE
Access token response with wrong expires_in

### ISSUE THREAD

**Issue by douglas-DS** [spring-projects/spring-authorization-server#1124]
**Bug Description**
When requesting an accessToken (`/oauth2/token`) the `expires_in` property generated by `Oauth2TokenEndpointFilter` and `OAuth2AccessTokenResponse.Buider`  is not based on the correct difference between `issuedAt` and the `expiresAt`.

**How To Reproduce**
- A custom implementation of `OAuth2ClientCredentialsAuthenticationProvider` that retrieves an existing `Oauth2Authorization.OAuth2AccessToken` for that particular client or generates a new one if none is found.
- Request a new access token (`/oauth2/token?grant_type=client_credentials` or whatever is based on your custom implementation).
- Request again an accessToken. At this point the inconsistency between the actual expiration of the token and the `expires_in` property in the response is evident.

**Expected behavior**
The response property `expires_in` implemented by `Oauth2TokenEndpointFilter` and `OAuth2AccessTokenResponse.Buider` should be generated based on the correct time difference between the `issuedAt` value and the token's expiration value (`expiresAt`).

**Sample**

A link to a GitHub repository with a [minimal, reproducible sample](https://github.com/douglas-DS/authorization-server-bug-sample). Just follow the [README](https://github.com/douglas-DS/authorization-server-bug-sample#how-to-reproduce) to reproduce the bug.

I really want to contribute with a PR, as far it's my first contribution to this project. Let me know if it's OK to send it.

**Comment by sjohnr** [comment]
Hi @douglas-DS. It seems your custom provider (from the sample) is re-using access tokens in the token request. This does not seem correct to me, so can you shed some light on why you are choosing to do this?

> The response property `expires_in` implemented by `Oauth2TokenEndpointFilter` and `OAuth2AccessTokenResponse.Buider` should be generated based on the correct time difference between the `issuedAt` value and the token's expiration value (`expiresAt`).

Do you mean to say that the `expires_in` field should be calculated based on the difference between "current time" and `expiresAt` instead of `issuedAt` and `expiresAt`?

**Comment by douglas-DS** [comment]
@sjohnr The purpose of this custom provider is reuse an existing token or create a new one, in other words a "getOrCreate" operation. This is an intentional behavior, since we have a SaaS scenario and multiple instances of the same client that would collapse if they were competing for a new accessToken on each internal operation.

**Comment by sjohnr** [comment]
Thanks for the explanation, @douglas-DS.

I do see your point. However, the existing response handler correctly calculates the `expires_in` property for a freshly generated token, as defined in the [spec](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-v2-1-05#section-3.2.3):

> "expires_in":    RECOMMENDED. The lifetime in seconds of the access token. For example, the value 3600 denotes that the access token will expire in one hour from the time the response was generated.

Since you've customized the `AuthenticationProvider` to re-use tokens which is not the intent of the token endpoint and not mentioned in the spec, I think you will need to provide your own `AuthenticationSuccessHandler` for the [`OAuth2TokenEndpointFilter`](https://docs.spring.io/spring-authorization-server/docs/current/reference/html/protocol-endpoints.html#oauth2-token-endpoint) as well. You can do so like this:

```java
authorizationServerConfigurer
	.tokenEndpoint((tokenEndpoint) -> tokenEndpoint
		.accessTokenResponseHandler((request, response, authentication) -> {
			// ...
		})
	);
```

I'm going to close this, as the provided explanation should be able to move you forward.

**Comment by douglas-DS** [comment]
No problem, @sjohnr. Tanks for the explanation and your time!

**Comment by douglas-DS** [comment]
@sjohnr  One more think I'd like to add, as describe here in the [spec](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-v2-1-05#section-3.2.3):

`"expires_in":
    RECOMMENDED. The lifetime in seconds of the access token. For example, the value 3600 denotes that the access token will expire in one hour from the time the response was generated`

In my opinion, that behavior should be implemented in the core of `spring-authorization-server` and no by a custom response handler as you mentioned earlier.
