### ISSUE TITLE
Update to nimbus-jose-jwt:9.31

### ISSUE THREAD

**Issue by sjohnr** [spring-projects/spring-authorization-server#1132]
Update to nimbus-jose-jwt:9.31

**Comment by stefanocke** [comment]
Meanwhile, this causes a dependency convergency error between Spring Auth Server 1.1.0 and Spring Boot 3.1  because of the downgrade to nimbus-jose-jwt:9.24.4 https://github.com/spring-projects/spring-security/commit/4ffece7e664340e1072287ad7a6d7ab2e005fd54

**Comment by stefanocke** [comment]
@jgrandja , the convergence error that we have seen came from `nimbus-jose-jwt` itself, wich comes as depenedency from spring-security-oauth2 , but also from spring authorization server itself, as seen above.
I was assuming, that it was caused by https://github.com/spring-projects/spring-security/commit/4ffece7e664340e1072287ad7a6d7ab2e005fd54 , since there the version of `com.nimbusds:nimbus-jose-jwt` has been downgraded from 9.31 to 9.24.4. But such a downgrade was not done in Spring Auth Server as well. Maybe I misunderstood the Spring Security issue, but we have definitely seen the convergence error above when using Spring Boot 3.1 + Spring Auth Server 1.1.0
