### ISSUE TITLE
How to update the authorization server user details using access/id tokens?

### ISSUE THREAD

**Issue by m-thirumal** [spring-projects/spring-authorization-server#1136]
Created new endpoint `/user` to update the user details. Header has access token, still the authorization is failed to invoke the user end point.

It will be nice to have this feature in authorization server..

**Context**
To update user email/phone number we need to access the authorization server using the access token.

**Comment by jgrandja** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it).
