### ISSUE TITLE
OidcUserInfoEndpointFilter leads to removal of SecurityContext from Session

### ISSUE THREAD

**Issue by stefanocke** [spring-projects/spring-authorization-server#1140]
**Describe the bug**
After the /userinfo endpoint is called, the SecurityContext is no longer available in the session and I have to login again.
The /userinfo endpoint is called from the OIDC client library in my frontend.

I debugged into the code and have noticed, that OidcUserInfoEndpointFilter and OidcClientRegistrationEndpointFilter are the only ones, that call SecurityContextHolder.clearContext() in a **finally** block.
The other filters like OAuth2TokenEndpointFilter only do this, if an exception occurs.

SecurityContextHolder.clearContext() in turn will lead to removal of SecurityContext from session in  org.springframework.security.web.context.HttpSessionSecurityContextRepository.SaveToSessionResponseWrapper.saveContext(SecurityContext)
It will determine, that "authBeforeExecution" was not null, but now it is null and will then call httpSession.removeAttribute(springSecurityContextKey)

Note:  saveContext() is called by SecurityContextPersistenceFilter in my case. I am on Spring Boot 2.7.x

**To Reproduce**
Use the getting started example.
Use an OIDC Client Lib in your UI that calls /userinfo enpoint, for example https://github.com/damienbod/angular-auth-oidc-client/ or fake some client by making REST calls and make sure to pass the session cookie when calling /userinfo endpoint.

**Expected behavior**
The security context in the session should not be removed.

**Comment by stefanocke** [comment]
As a workaround, I switched from SecurityContextPersistenceFilter to SecurityContextHolderFilter:
```
 http.securityContext((securityContext) -> securityContext.requireExplicitSave(true));
```

**Comment by jgrandja** [comment]
@stefanocke The issue you are having with

> the SecurityContext is no longer available in the session and I have to login again

is because

> fake some client by making REST calls and **make sure to pass the session cookie** when calling /userinfo endpoint

As stated in the spec, the [UserInfo endpoint](https://openid.net/specs/openid-connect-core-1_0.html#UserInfo):

> The UserInfo Endpoint is an **OAuth 2.0 Protected Resourc**e that returns Claims about the authenticated End-User. To obtain the requested Claims about the End-User, **the Client makes a request to the UserInfo Endpoint using an Access Token** obtained through OpenID Connect Authentication.

The users session cookie **should not** be passed in the UserInfo request. It is expected that the Client will pass a bearer access token to the UserInfo endpoint for authorization. The call to `SecurityContextHolder.clearContext()` is expected as we do not want to persist the `Authentication` since the expected `Authentication` instance is a bearer access token (e.g. `JwtAuthenticationToken`).

I'm going to close this as the current implementation is correct. Please correct your client as it should not pass the user's session cookie and should simulate an OAuth2 client protected resource call and pass a bearer access token.
