### ISSUE TITLE
Unhandled NPE in OAuth2TokenIntrospectionAuthenticationProvider.

### ISSUE THREAD

**Issue by tenvapa** [spring-projects/spring-authorization-server#1145]
**Describe the bug**
By documentation the RegisteredClientRepository.findById(String id) should return the found RegisteredClient or null if not found. But in OAuth2TokenIntrospectionAuthenticationProvider -> 109 row, when calling the RegisteredClientRepository.findById(String id) a null check is not there and the authorized client is directly passed to withActiveTokenClaims() method where the authorizedClient.getClientId() is called which produces NPE.
**To Reproduce**
Steps to reproduce the behavior.
Implement the RegisteredClientRepository contract and make the findById(String id) return null. Then introspect a token and the npe is thrown.
**Expected behavior**
Like in every other place I found in the project just check if RegisteredClientRepository.findById(String id) is null  and throw an exception:
throw new DataRetrievalFailureException("The RegisteredClient with id '" + registeredClientId + "' was not found in the RegisteredClientRepository.");
**Sample**

A link to a GitHub repository with a [minimal, reproducible sample](https://stackoverflow.com/help/minimal-reproducible-example).

Reports that include a sample will take priority over reports that do not.
At times, we may require a sample, so it is good to try and include a sample up front.

**Comment by jgrandja** [comment]
@tenvapa 

> when calling the RegisteredClientRepository.findById(String id) a null check is not there and the authorized client is directly passed to withActiveTokenClaims() method where the authorizedClient.getClientId() is called which produces NPE

A `null` check is not required if the `OAuth2Authorization` is found in the previous call to `this.authorizationService.findByToken(token ...`, since it's expected that the `RegisteredClient` MUST exist if an `OAuth2Authorization` to exists.

The case you described reveals an inconsistent state in the underlying persistence store. This should be investigated and fixed. An `OAuth2Authorization` should not exist if the associated `RegisteredClient` does not exist.

I'm going to close this as the underlying persistence store is in an inconsistent state and should be investigated and fixed.
