### ISSUE TITLE
Client secret that contains + not supported

### ISSUE THREAD

**Issue by frederikz** [spring-projects/spring-authorization-server#1149]
A client with client_credentials and a client secret that containts + can't authenticate.
The reason is that org.springframework.security.oauth2.server.authorization.web.authentication.ClientSecretBasicAuthenticationConverter URL-decodes userid and password obtained from the Basic Auth header. I don't see that rfc2617 states that userid and password are URL-encoded. The standard Spring security org.springframework.security.web.authentication.www.BasicAuthenticationConverter also doesn't URL-decode the userid and password.
Don't URL-decode clientID and clientSecret obtained from the Base64-encoded Basic auth header.

**Comment by csmithmtb** [comment]
Please reconsider this issue.  

Spring's own WebClient.headers(h -> h.setBasicAuth()) doesn't use URLEncode the values before Base64ing the values together.  Thus, setBasicAuth("client-with-plus-sign", "Client+Password") results in an Auth header of base64 encoded, "client-with-plus-sign:Client+Password" instead of "client-with-plus-sign:Client%2bPassword"
