### ISSUE TITLE
I wonder if there is any good way to compress the length of tokens, such as Deflater and Inflater

### ISSUE THREAD

**Issue by opcooc** [spring-projects/spring-authorization-server#1188]
**Expected Behavior**

**Current Behavior**

**Context**

**Comment by sjohnr** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/questions/tagged/spring-security). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces this issue if you feel this is a genuine bug.
