### ISSUE TITLE
JdbcOAuth2AuthorizationService seems to pile up tokens

### ISSUE THREAD

**Issue by rcaspar** [spring-projects/spring-authorization-server#1227]
**Describe the bug**
When I request a token (client credentials), I always end-up with a new one

**To Reproduce**
```(bash)
curl --request POST \
  --url http://xxxxxx/oauth2/token \
  --header 'Authorization: Basic xxxxxxxxx' \
  --data client_id=xxxxx \
  --data 'client_secret=xxxxxxx' \
  --data grant_type=client_credentials \
  --data scope=xxx && curl --request POST \
  --url http://xxxxxx/oauth2/token \
  --header 'Authorization: Basic xxxxxxxxx' \
  --data client_id=xxxxx \
  --data 'client_secret=xxxxxxx' \
  --data grant_type=client_credentials \
  --data scope=xxx
```

**Expected behavior**
Token from the first request is used in second request response

I think the issue is due to the usage of org.springframework.security.oauth2.server.authorization.JdbcOAuth2AuthorizationService#findById, a composite key: client_id, principal_name, grant_type and scopes might be a better key to find an existing token

**Comment by jgrandja** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces this issue if you feel this is a genuine bug.
