### ISSUE TITLE
Make all utils classes public

### ISSUE THREAD

**Issue by akuma8** [spring-projects/spring-authorization-server#1290]
I am currently implementing custom grant type and I use existing grant types as example. 
The issue is that I have to copy-paste existing utils classes  like those present in `org.springframework.security.oauth2.client.jackson2` package or in `org.springframework.security.oauth2.server.authorization.config.annotation.web.configurers` because they are package private. 
It would be nice to have access to them to help developers. 
Thank you

**Comment by mrFlick72** [comment]
I do not know if this page can help you` https://docs.spring.io/spring-authorization-server/docs/current/reference/html/guides/how-to-ext-grant-type.html`

but I think that in the past like 0.2 I agree with you, I implemented password flow for some legacy integration and was hard to do that but now should be better the support.

I can not say that it solve your issue 100% because the migration was done by some one else but who makes the porting said to me that the guide how-to-ext-grant-type. helps a lot

**Comment by akuma8** [comment]
@mrFlick72 I followed that page 

> I do not know if this page can help you https://docs.spring.io/spring-authorization-server/docs/current/reference/html/guides/how-to-ext-grant-type.html

I followed that page to implement the password grant type see my gist: https://gist.github.com/akuma8/2eb244b796f3d3506956207997fb290f
As you can see I had to copy all utils classes and add them in my source code. I think those utils classes shoud be accessible to everyone.

**Comment by jgrandja** [comment]
@akuma8 I took a look at your gist and you don't need to copy `OAuth2ConfigurerUtils`. Instead, you can define an `OAuth2TokenGenerator<?>` `@Bean` the same way the [guide](https://docs.spring.io/spring-authorization-server/docs/current/reference/html/guides/how-to-ext-grant-type.html#configure-token-endpoint) does and inject that.

As for the other copied and used methods:
- `OAuth2AuthenticationProviderUtils.getAuthenticatedClientElseThrowInvalidClient()`
- `OAuth2EndpointUtils.getParameters()`
- `OAuth2EndpointUtils.throwError()`

These utility methods are intended for internal use only and there are no plans to expose them. Furthermore, the code in each of those methods is quite minimal so I would recommend copying the implementation code into your custom grant components instead of copying the whole class.
