### ISSUE TITLE
Authorization request failed: [invalid_request] OAuth 2.0 Parameter: redirect_uri

### ISSUE THREAD

**Issue by cavgaet** [spring-projects/spring-authorization-server#1300]
**Describe the bug**
While use a properties instead yml file in simple client, the server results in a OAuth2AuthorizationCodeRequestAuthenticationException: OAuth 2.0 Parameter: redirect_uri and the client receive status 500.

**To Reproduce**
Adjust the same application.yml.

**Expected behavior**
It result in the exception.

**Comment by sjohnr** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/questions/tagged/spring-security). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces this issue if you feel this is a genuine bug.
