### ISSUE TITLE
JWT token without jti now. This should be added.

### ISSUE THREAD

**Issue by jinsulive** [spring-projects/spring-authorization-server#1308]
Now I find that no jti claim in the jwt token of this project in org.springframework.security.oauth2.server.authorization.token.JwtGenerator#generate. will this be added in the future?

**Comment by sjohnr** [comment]
@jinsulive, thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/questions/tagged/spring-security). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces this issue if you feel this is a genuine bug.

Having said that, if you believe you have a genuine enhancement to suggest, please provide additional details and we can look more into the issue. As it is, I would need to know more about your use case. Ideally, enhancement suggestions would not be phrased as questions.

**Comment by ccobham** [comment]
@sjohnr I came across this issue while I was looking for similar functionality today and thought I might add a bit of context to the original question.

The [JWT specification](https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.7) defines an optional claim, ``jti``, which serves as a unique identifier for the JWT. This is a useful addition to support token revocation lists.

In the case that Spring Authorization Server's token revocation endpoint is invoked, while the authorization server is aware that the token is no longer valid, resource servers using JWT-based access tokens have no way of knowing this event occurred unless they call the token introspection endpoint on every request. The increased latency from this additional network hop might be unacceptable in certain use cases.

Once possible implementation would be for the authorization server to push a revocation list to registered resource servers in addition to marking the token as invalidated in its backend. Rather than pushing raw unexpired JWTs in this list (or a hash of the JWT), it would be useful to push the token identifier (``jti``) instead. The resource server could store the ``jti`` in a cache for the remainder of the JWT's lifetime and perform a quick cache check while validating the JWT for each request to make sure it hasn't been revoked at the authorization server.


As an example, [Amazon Cognito](https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-the-access-token.html) provides two claims, ``jti`` and ``origin_jti`` on access tokens it issues. If you revoke a Cognito token, Cognito invalidates any token with the same ``origin_jti`` value.

**Comment by sjohnr** [comment]
@jinsulive thanks for the additional context.

Please note that adding the `jti` claim is straightforward by providing an [`OAuth2TokenCustomizer`](https://docs.spring.io/spring-authorization-server/reference/core-model-components.html#oauth2-token-customizer).

Since token revocation lists and related functionality are not built-in (and therefore custom) and likely will remain so, I think this optional claim should remain a customization on your end as well. If I'm missing anything or if there is a specific use case that could require every deployment to need `jti`, please open an issue with those details and we can go from there.
