### ISSUE TITLE
tokenIntrospectionEndpoint No catch exception

### ISSUE THREAD

**Issue by imaxun** [spring-projects/spring-authorization-server#1310]
<img width="729" alt="image" src="https://github.com/spring-projects/spring-authorization-server/assets/29112991/fb3bc346-8af1-410d-a559-d4d7c55b849c">

<img width="1098" alt="image" src="https://github.com/spring-projects/spring-authorization-server/assets/29112991/b22a67c6-0c46-48ce-bc7b-444326ba8f23">

<img width="1021" alt="image" src="https://github.com/spring-projects/spring-authorization-server/assets/29112991/1d9f047d-38ca-4231-a7ee-487ab8759b8c">

**Comment by imaxun** [comment]
Unable to perform exception interception when I customize the exception

**Comment by sjohnr** [comment]
@imaxun, thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/questions/tagged/spring-security). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces this issue if you feel this is a genuine bug.
