### ISSUE TITLE
How-to: save OAuth2Authorization object in mongo db and retrieve it from db 

### ISSUE THREAD

**Issue by Moh3n75** [spring-projects/spring-authorization-server#1312]
i hava this config 

```
@Configuration
@RequiredArgsConstructor
public class SimpleMongoConfig {

    @Value("${spring.data.mongodb.uri}")
    private String uri;

    @Value("${spring.data.mongodb.database}")
    private String db;
    private final RegisteredClientRepository registeredClientRepository;

    @Bean
    public MongoClient mongoClient() {
        return MongoClients.create(uri);
    }


    @Bean
    public MongoTemplate mongoTemplate() throws Exception {
        MongoTemplate template = new MongoTemplate(mongoClient(), db);
        MappingMongoConverter mmc = (MappingMongoConverter) template.getConverter();
        mmc.setCustomConversions(mongoCustomConversions(mmc));
        mmc.setMapKeyDotReplacement("_DOT_");
        mmc.afterPropertiesSet();
        return template;
    }

    public MongoCustomConversions mongoCustomConversions(MappingMongoConverter mmc) {
        return new MongoCustomConversions(List.of(new MongoDbOauth2AuthorizationService.OAuth2AuthenticationReadConverter(registeredClientRepository,mmc)));
    }
}
```
 and write this service 

`public class MongoDbOauth2AuthorizationService implements OAuth2AuthorizationService `

and used in my configuration 

```
@Bean
    public OAuth2AuthorizationService authorizationService(MongoTemplate mongoTemplate, RegisteredClientRepository registeredClientRepository) {
        return new MongoDbOauth2AuthorizationService(mongoTemplate, registeredClientRepository);
    }
```

but when i call method` public OAuth2Authorization findByToken(String token, OAuth2TokenType tokenType) `
by `mongoTemplate` get error 

> Failed to instantiate org.springframework.security.web.authentication.WebAuthenticationDetails using constructor NO_CONSTRUCTOR with arguments 

how can retrieve information in mongodb

**Comment by sjohnr** [comment]
@Moh3n75, if you're requesting a how-to guide, please see gh-1019 as this would be a duplicate.

If you're simply asking a question, note that it would be better suited to [Stack Overflow](https://stackoverflow.com/questions/tagged/spring-security). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces this issue if you feel this is a genuine bug.

Please keep in mind that when asking questions on stackoverflow, more details would be needed as I don't see enough information in your question to be able to provide much help. I'm going to close this for now.
