### ISSUE TITLE
how to use postLogoutRedirectUris?

### ISSUE THREAD

**Issue by LuoHong1993** [spring-projects/spring-authorization-server#1319]
**Expected Behavior**

**Current Behavior**

**Context**

 
how to use postLogoutRedirectUris? Is there an example?

**Comment by ddubson** [comment]
You may find an example of configuring post logout redirect URIs in this [merged PR](https://github.com/spring-projects/spring-authorization-server/pull/1161/files).

**Comment by jgrandja** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it).
