### ISSUE TITLE
The first authorization will fail.

### ISSUE THREAD

**Issue by hezhongfeng** [spring-projects/spring-authorization-server#1321]
**Describe the bug**
Run Authorization Server and Run Client, then Go to `http://127.0.0.1:8080`

I've tried several times.

**To Reproduce**

The first authorization will fail.

**Expected behavior**

The first authorization will succeed.

**Sample**

just run the samples

<img width="1178" alt="image" src="https://github.com/spring-projects/spring-authorization-server/assets/12163050/d8c7dfaf-cc85-4842-b980-330964d66ea5">

**Comment by jgrandja** [comment]
@hezhongfeng The reason the first authorization fails is because you started the flow using `http://localhost:8080/`, which results in a session cookie overwrite between the client app and authorization server app since they both write cookies under localhost. As indicated in the sample [README](https://github.com/spring-projects/spring-authorization-server/tree/main/samples#demo-sample):

> Go to `http://127.0.0.1:8080/`

This way the client app session cookie is stored under `http://127.0.0.1` and the authorization server session cookie is stored under `http://localhost`.

**Comment by hezhongfeng** [comment]
thanks for your answer.
