### ISSUE TITLE
Get OAuth2AccessTokenResponse by access_token in the Controller

### ISSUE THREAD

**Issue by Waylon-Firework** [spring-projects/spring-authorization-server#1331]
**Expected Behavior**

When login by authorization_code, we will get the response below:

```
{
    "access_token": "ttt",
    "refresh_token": "uuuu",
    "scope": "openid profile message.read",
    "id_token": "ccc",
    "token_type": "Bearer",
    "expires_in": 299
}
```

Some times, we want to check some thing, we want to create an api, such as token/info, we want to use the api to return the response above again when fe call the api and pass the bearer token. Is it possible?

**Comment by rishiraj88** [comment]
I, too, like to learn it.

**Comment by jgrandja** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it).
