### ISSUE TITLE
How to implement single sign-on between client system 1 and client system 2

### ISSUE THREAD

**Issue by CollectBugs** [spring-projects/spring-authorization-server#1332]
**Problem Background**
I have checked a lot of information, but there is no sample information that introduces how to implement single sign-on in the front-end and back-end separation architecture

**Problem Description**
The client system 1 login page is /login/client1.html
The client system 2 login page is /login/client2.html

How to use spring-authorization-server to realize single sign-on between client system 1 and client system 2 and its principle？

**Comment by jgrandja** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it).
