### ISSUE TITLE
 Feature Request: Allow Updating clientId without Changing the id

### ISSUE THREAD

**Issue by yonyes** [spring-projects/spring-authorization-server#1354]
While working with the Spring Authorization Server and using a physical database, I've identified a limitation in the `JdbcRegisteredClientRepository` class that prevents updating the `clientId` without changing the id. Specifically, the line [here](https://github.com/spring-projects/spring-authorization-server/blob/99cd1b8d1ebd280faac54ea27c92bd8dc376fa2d/oauth2-authorization-server/src/main/java/org/springframework/security/oauth2/server/authorization/client/JdbcRegisteredClientRepository.java#L138) (`parameters.remove(0)`) seems to be the root cause.

Use Case:
In scenarios where there might be a typo in the `clientId` or a need to rotate it for other reasons, and we don't want to change the id because it would require unnecessary work (like removing the old client, reconfiguring applications, etc.), the current implementation doesn't support this.

Proposed Solution:
Consider removing or adjusting the line `parameters.remove(0)` in the `JdbcRegisteredClientRepository` class to allow for updating the clientId without affecting the id.

Benefits:

Provides more flexibility in managing client registrations, especially in cases of typos or minor adjustments.
Avoids the need for extensive changes or direct database manipulations which can be error-prone.
Simplifies the process of updating client details without affecting the primary key.

**Comment by jgrandja** [comment]
@yonyes The `id` and `client_id` are meant to be a composite key. It doesn't make sense to allow the `client_id` to be updated for a specific `id`. This effectively makes it a new client since `client_id` uniquely identifies the client in oauth2 flows..

> In scenarios where there might be a typo in the `clientId` or a need to rotate it for other reasons

For typos, why can't you delete the client registration and re-add it? And how often does a typo happen?
For the need to rotate....what exactly are you rotating? Typically the `client_secret` would be rotated.

I don't see a need to make any changes at this point as `id` and `client_id` are meant to be a composite key. The `id` is for internal (persistence) use and `client_id` is for external use for oauth2 flows.

I'm going to close this but if you have other user cases then we can consider re-opening and continuing the discussion.
