### ISSUE TITLE
Expired ID tokens are rejected at the authorization server on an RP-initiated logout

### ISSUE THREAD

**Issue by sjohnr** [spring-projects/spring-authorization-server#1440]
**Describe the bug**

Expired ID tokens are rejected at the authorization server on an RP-initiated logout.

**To Reproduce**

Using the included samples:

1. Log in with the client using OIDC.
2. Wait 30 minutes.
3. Log out using RP-initiated logout and receive a 400 error for `id_token_hint` parameter.

**Expected behavior**

Per the [OpenID Connect RP-Initiated Logout 1.0](https://openid.net/specs/openid-connect-rpinitiated-1_0.html#RPLogout) specification:

> The OP SHOULD accept ID Tokens when the RP identified by the ID Token’s aud claim and/or sid claim has a current session or had a recent session at the OP, **even when the exp time has passed.**

**Comment by maradanasai** [comment]
Hi @sjohnr Thanks for reporting this. I'm able to reproduce this, thought of reporting it here

**Comment by VithouJavaMaestro** [comment]
I'm encountering an issue where **_OidcClientInitiatedServerLogoutSuccessHandler_** uses the original ID Token issued during the first login, rather than the most recent one.

In OAuth2RefreshTokenAuthenticationProvider, around line 247, the following code is executed:

`
authorization = authorizationBuilder.build();
this.authorizationService.save(authorization);
`
Each time a refresh token is used, this code saves a new OAuth2Authorization that contains a new ID Token, overwriting the previous authorization entry in the store.

However, during logout, **_OidcClientInitiatedServerLogoutSuccessHandler_** seems to retrieve the ID Token issued during the original login, not the updated one from the most recent refresh.

This leads to issues in logout flows that rely on the latest ID Token to complete the logout process correctly.
