### ISSUE TITLE
There are no transaction demarcations when using the jdbc repositories, leading to race conditions and potentially halfway updated state on crashes

### ISSUE THREAD

**Issue by geirhede** [spring-projects/spring-authorization-server#1444]
I have a bare-bones spring authorization server example up and running, and I have wired in jdbc-based user, client and authorization persistence.

So I am reading through the code, and around about [the bit of the authorization code provider that invalidates a code that has been used](https://github.com/spring-projects/spring-authorization-server/blob/cf801c36927172e5a19d29afd1e75be3b9571795/oauth2-authorization-server/src/main/java/org/springframework/security/oauth2/server/authorization/authentication/OAuth2AuthorizationCodeAuthenticationProvider.java#L142) there is a race condition if the database runs with autocommit on - it is conceivable that another thread might get to read a valid token in between the if test checking if the authorization code is valid and persisting an invalid state. AFAICT the only way to avoid this kind of race condition is to properly demarcate transaction boundaries to ensure atomic operation and doing "select for update" to grab a row lock.

I have set hikari.auto-commit: false in my application config and confirmed that my previously working tests started failing. I don't seem to have missed any magic that handles transactions. I also asked on stackoverflow if I missed how transactions were meant to work, and didn't get an answer, so I am assuming this was forgotten, which prompted me to write this report.

The in-memory versions of the repositories have similar issues, but I feel these are not not meant for production use. Should they be marked as such in the log when the server starts?

I would expect the providers to deliver basic ACID properties on operations because
- race conditions are bad. We are dealing with a six-digit number of operations per day, and at this volume we are going to experience those race conditions at some point
- potentially halfway updated state after a crash is hard to cope with from an operations standpoint. It makes the hosting manual explode in size.
- if we were to do a security review on the providers, as they stand, we would have to deal with the whole state tree containing potentially partially updated states in order to be able to explain why the code is safe. That would be very, very time consuming and borderline impossible.

If you agree I would be happy to help do the grunt work of adding the logic, provided I get some help figuring out how you would want the code to look.

**Comment by jgrandja** [comment]
@geirhede Please see this [comment](https://github.com/spring-projects/spring-authorization-server/issues/995#issuecomment-1344888214).

Spring Authorization Server is not in the business of persistence or configuring data access and transactional boundaries. Instead, it's sole business is OAuth2/OIDC Application Security.

As noted in the linked comment, `JdbcOAuth2AuthorizationService` is a simplified JDBC implementation that **MAY** be used in production. **However, the expectation is that the consuming application will provide their own implementation of `OAuth2AuthorizationService` that has the ability to scale in a production-grade environment.** The `JdbcOAuth2AuthorizationService` does have some limitations as it won't scale or perform well in a high throughput production environment.

> We are dealing with a six-digit number of operations per day, and at this volume we are going to experience those race conditions at some point

I would recommend that you provide your own implementation of `OAuth2AuthorizationService` so that you have full control and the ability to fine-tune performance to your environment.

Furthermore, transactional boundaries is an architectural decision that the consuming application must define. Introducing transactional boundaries is obviously important but if not configured at the right points, it can erode performance. This decision must be made by the consuming application as the requirements vary from one application to the next.

Lastly, transaction demarcation doesn't necessarily start at the `OAuth2AuthorizationService` as it can be decided to start earlier at the `AuthenticationProvider` if the application requirements specify this. And all of this can be configured using a delegation-based strategy instead of annotating the "real" implementations. Additionally, take a look at Spring Frameworks support for [Transaction Management](https://docs.spring.io/spring-framework/reference/data-access/transaction.html) for further details.

I'm going to close this as we're not looking to add transactional annotations to `JdbcOAuth2AuthorizationService`.

**Comment by geirhede** [comment]
@jgrandja Ok, that is good information to know. I do think be a good idea to put some documentation in the Jdbc<whatever> classes if they are not meant to be production-quality to guide your users away from thinking they are, along the lines of what can be found in InMemoryRegisteredClientRepository. 

If nothing else it will stop people from doing quality assessments with an eye to putting it into production, like I just did.

**Comment by jgrandja** [comment]
@geirhede Good idea

> I do think be a good idea to put some documentation in the Jdbc classes if they are not meant to be production-quality

I just pushed an update to the javadoc for the JDBC implementations starting from `0.4.x` to `main` in this [commit](https://github.com/spring-projects/spring-authorization-server/commit/d52edb8f769891811358bda27bf188a6bc200e6a).

**Comment by OrangeDog** [comment]
How, for example, should the transaction boundaries be added for the `JdbcOAuth2AuthorizationConsentService`? Presumably around the `AuthenticationProvider.authenticate` method? However, because the classes are all `final` it cannot be done nicely with any AOP techniques.

IMO they should be transactional out of the box, so they actually work correctly. If auto-commit is on then there are buggy race conditions, and if it's off (which is the usual for production systems) then nothing is ever committed at all.

If they're not performant enough then that is fine and the warnings are already there, but they should have the basic functionality working and be aware of transactions.

**Comment by OrangeDog** [comment]
This seems to be a reasonably sane way to deal with it in the meantime:

```java
@RequiredArgsConstructor
public class TransactionalAuthenticationProvider implements AuthenticationProvider {
    private final @Delegate AuthenticationProvider delegate;

    @Transactional
    public Authentication authenticate(Authentication authentication) throws AuthenticationException {
        return delegate.authenticate(authentication);
    }
}

@Bean 
public SecurityFilterChain authorizationServerFilterChain(HttpSecurity http) throws Exception {
    return http
        .securityMatcher(authorizationServerConfigurer.getEndpointsMatcher())
        .with(authorizationServerConfigurer, oauth -> oauth
            .authorizationEndpoint(endpoint -> endpoint
                .authenticationProviders(providers -> providers.replaceAll(TransactionalAuthenticationProvider::new))
            ))
        .authorizeHttpRequests(authorize -> authorize.anyRequest().authenticated())
        .build();
}
```
