### ISSUE TITLE
Each instance of Spring Auth Server exposes its own JWKS information

### ISSUE THREAD

**Issue by adamleantech** [spring-projects/spring-authorization-server#1462]
When running multiple instances of the Spring Authorization Server behind a gateway/load balancer, the resource servers can't always authenticate. This is because the resource servers only have knowledge of the well known configuration endpoint of one of the instances, not all, as a call to the JWKS endpoint will return only the key information known to that instance of Spring Auth Server. This sometimes prevents the resource server from getting the correct key to decode the JWT token.

I would expect some mechanism to coordinate the well known configuration provided by multiple instances (perhaps something similar to session sharing using Redis?).

Please note that I found a similar query [here](https://stackoverflow.com/questions/77125525/multiple-instances-of-spring-authorization-server#77125525)

**Comment by jgrandja** [comment]
@adamleantech I'm going to close this as this is a question that should be asked on [Stack Overflow](https://stackoverflow.com/). We prefer to use GitHub issues only for bugs and enhancements.

Furthermore, this appears to be more of a configuration issue on the resource server side so that it can support multiple authorization servers. If this is the case, then this is a Spring Security configuration. Please ses the [ref doc](https://docs.spring.io/spring-security/reference/servlet/oauth2/resource-server/multitenancy.html#oauth2resourceserver-multitenancy).

**Comment by adamleantech** [comment]
thanks for pointing me in the direction of the docs.  Would be helpful if you could answer the SO question that I linked 🙏
