### ISSUE TITLE
The version of the jar package introduced in the class does not match, and the reference class is missing

### ISSUE THREAD

**Issue by springclous** [spring-projects/spring-authorization-server#1473]
In Class `org.springframework.security.oauth2.server.resource.introspection.NimbusOpaqueTokenIntrospector.java` , the introduced jar package `nimbus-jose-jwt-9.24.4.jar `does not include the following classes, resulting in program startup errors
![image](https://github.com/spring-projects/spring-authorization-server/assets/53843614/84f6fe6b-0c21-403a-a411-61d8d3ffcfa8)

**Comment by jgrandja** [comment]
@springclous `NimbusOpaqueTokenIntrospector` lives in Spring Security not Spring Authorization Server. Please log the issue there.

As well, the details provided in this issue is quite minimal so please ensure you add a lot more details and a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) reproducing the issue would help.
