### ISSUE TITLE
Concurrent session control is working when used with spring authorization server

### ISSUE THREAD

**Issue by RajeevKumarMarrapu** [spring-projects/spring-authorization-server#1523]
I have used the demo-authorization-server impl. provided in samples section to see how spring authorization server handles the users concurrent session. I would like to expire the oldest logged in user session if exceeds the limits so used the sessionManagment() dsl but it is not working here (username/password login or with oauth2 login).

I was able to login multiple times and can access data from both the sessions, which is not expected (I have set maxSessions as 1). I have created the beans for http session events publisher and session registry impl. Can someone please test why this is happening? cc: @sjohnr @jgrandja

**Comment by sjohnr** [comment]
@RajeevKumarMarrapu, thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/questions/tagged/spring-security). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces this issue if you feel this is a genuine bug.

Having said that, I believe this is a cross-post [from stackoverflow](https://stackoverflow.com/questions/76470726/how-to-implement-session-management-in-spring-authorization-server#comment137290022_76470726). I have commented on the question and do not see a reply. Please reply on the question and I'll be happy to take another look.
