### ISSUE TITLE
Adding clientSettings parameters for Dynamic Client Registration(POST /connect/register)

### ISSUE THREAD

**Issue by requizm** [spring-projects/spring-authorization-server#1530]
**Expected Behavior**
I want to change the default settings of `requireProofKey` and `requireAuthorizationConsent` fields. 

**Current Behavior**
Currently it's [hardcoded](https://github.com/spring-projects/spring-authorization-server/blob/a04b336a0cdc70279d3de4415685776e99f1581b/oauth2-authorization-server/src/main/java/org/springframework/security/oauth2/server/authorization/oidc/converter/OidcClientRegistrationRegisteredClientConverter.java#L98). There is no settings field in [the converter](https://github.com/spring-projects/spring-authorization-server/blob/a04b336a0cdc70279d3de4415685776e99f1581b/oauth2-authorization-server/src/main/java/org/springframework/security/oauth2/server/authorization/oidc/OidcClientMetadataClaimNames.java#L33).

**Context**
I have dynamic clients that shouldn't need a consent step. I could probably make a workaround by creating a custom converter. In my case, I have a custom `RegisteredClientRepository`  implementation for DB. I just need to overwrite `clientSettings`. Anyway, a workaround is possible but I prefer to set `clientSettings` in the rest body.

**Comment by jgrandja** [comment]
@requizm 

> I could probably make a workaround by creating a custom converter

`OidcClientRegistrationAuthenticationProvider.setRegisteredClientConverter()` is the intended hook for customizing the `RegisteredClient`. You can reuse the existing `OidcClientRegistrationRegisteredClientConverter` and implement a delegation-based strategy to simply override the default `clientSettings` as follows:

```java
public class CustomOidcClientRegistrationRegisteredClientConverter implements Converter<OidcClientRegistration, RegisteredClient> {
	private final Converter<OidcClientRegistration, RegisteredClient> clientRegistrationRegisteredClientConverter
			= new OidcClientRegistrationRegisteredClientConverter();

	@Override
	public RegisteredClient convert(OidcClientRegistration clientRegistration) {
		RegisteredClient registeredClient = this.clientRegistrationRegisteredClientConverter.convert(clientRegistration);
		ClientSettings clientSettings = ClientSettings.builder().requireAuthorizationConsent(false).build();
		return RegisteredClient.from(registeredClient).clientSettings(clientSettings).build();
	}

}
```

> I prefer to set `clientSettings` in the rest body

The `clientSettings` is not defined in the [OpenID Connect Dynamic Client Registration 1.0](https://openid.net/specs/openid-connect-registration-1_0.html) spec as parameters so we would not add this support since it would not be spec compliant.

I'm going to close this as the intended customization hook is `OidcClientRegistrationAuthenticationProvider.setRegisteredClientConverter()`.
