### ISSUE TITLE
Customize the sendAuthorizationConsent in OAuth2DeviceVerificationEndpointFilter .

### ISSUE THREAD

**Issue by opcooc** [spring-projects/spring-authorization-server#1602]
**Expected Behavior**

I want to trigger different behaviors (redirect or return JSON) through different parameters, and I'm not sure if this is feasible

**Current Behavior**

**Context**

**Comment by jgrandja** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it).
