### ISSUE TITLE
Introspection can't work

### ISSUE THREAD

**Issue by yanggang3390** [spring-projects/spring-authorization-server#1606]
http.authorizeHttpRequests(authorize -> {
                            authorize.anyRequest().authenticated();
                        }
                )
                .oauth2ResourceServer(oauth2 -> oauth2
                        .opaqueToken(opaqueToken -> opaqueToken
                                        .introspectionUri("http://localhost:9000/introspect")
                                        .introspectionClientCredentials("platform-client", "secret"))

//                        .jwt(Customizer.withDefaults())
                        .authenticationEntryPoint(new MyAuthenticationEntryPoint())
                        .accessDeniedHandler(new MyAccessDeniedHandler())

                );
        return http.build();

Every correct token is a token failure

Do I need to add any configuration to the authentication server？

**Comment by jgrandja** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces this issue if you feel this is a genuine bug.
