### ISSUE TITLE
Support account selection logic similar to Google OAuth2.

### ISSUE THREAD

**Issue by chenzhenjia** [spring-projects/spring-authorization-server#1670]
I hope to add a new authorization logic in `OAuth2AuthorizationCodeRequestAuthenticationProvider`, similar to `authorizationConsentRequired`. Currently, I can only copy all the code into my custom `AuthenticationProvider`, and every time I upgrade `spring-authorization-server`, I need to compare whether there have been changes. 
Below is my example code:
```java
  @Override
  public Authentication authenticate(Authentication authentication) throws AuthenticationException {
    // copy code .....
    OAuth2Authorization authorization;
    // ---------------
    // Select account
    // ---------------
    String selectAccountState = (String) authorizationCodeRequestAuthentication
        .getAdditionalParameters().get(CustomOAuth2ParameterNames.SELECT_ACCOUNT_STATE);

    if (!StringUtils.hasText(selectAccountState)) {
      String state = stateGenerator.generateKey();
      authorization = authorizationBuilder(registeredClient, principal, authorizationRequest)
          .attribute(CustomOAuth2ParameterNames.SELECT_ACCOUNT_STATE, state).build();

      if (this.logger.isTraceEnabled()) {
        logger.trace("Generated authorization select account state");
      }

      this.authorizationService.save(authorization);
      Set<String> requestScopes = authorizationCodeRequestAuthentication.getScopes();
      if (this.logger.isTraceEnabled()) {
        this.logger.trace("Saved authorization");
      }

      return new OAuth2AuthorizationSelectAccountAuthenticationToken(
          authorizationRequest.getAuthorizationUri(), registeredClient.getClientId(), principal,
          state, requestScopes, null);
    } else {
      authorization = authorizationService.findByToken(selectAccountState,
          new OAuth2TokenType(CustomOAuth2ParameterNames.SELECT_ACCOUNT_STATE));
      if (authorization == null) {
        throwError(OAuth2ErrorCodes.INVALID_GRANT, CustomOAuth2ParameterNames.SELECT_ACCOUNT_STATE,
            authorizationCodeRequestAuthentication, registeredClient);
      }
      if (!principal.getName().equals(authorization.getPrincipalName())) {
        throwError(OAuth2ErrorCodes.INVALID_REQUEST, OAuth2ParameterNames.STATE,
            authorizationCodeRequestAuthentication, registeredClient);
      }

      authorization = OAuth2Authorization.from(authorization).attributes(attrs -> {
        attrs.remove(CustomOAuth2ParameterNames.SELECT_ACCOUNT_STATE);
      }).build();
    }
    // ---------------
    // select account off
    // ---------------
    // copy code .....
  }
```

**Comment by jgrandja** [comment]
@chenzhenjia The [OpenID Connect Authentication Request](https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest) `prompt` parameter specifies `select_account` as one of the values for this use case.

The account selection step occurs during the authentication process as the authentication sub-system would be aware of the active sessions for the user and is also responsible for the management of the user sessions. The authorization server and the authentication sub-system are completely different systems so the sample code you provided in `OAuth2AuthorizationCodeRequestAuthenticationProvider` would not be the right place to have this logic. The account selection logic must reside in the authentication sub-system.

I'm not sure what authentication mechanism you are using (`formLogin()`, SAML, Active Directory, etc.) but this is typically configured with Spring Security authentication and related integrations.

I'm going to close this since account selection logic belongs in the authentication sub-system and not the authorization server.

Lastly, I would not recommend having this logic in `OAuth2AuthorizationCodeRequestAuthenticationProvider` as you currently have in your custom implementation. Instead, you can provide a custom `AuthenticationConverter` very similar to `OAuth2AuthorizationCodeRequestAuthenticationConverter` that checks for `CustomOAuth2ParameterNames.SELECT_ACCOUNT_STATE`, and if present, then ensure you return `OAuth2AuthorizationCodeRequestAuthenticationToken.getPrincipal()` as `!isAuthenticated()` so that the `OAuth2AuthorizationEndpointFilter` [continues with the `filterChain`](https://github.com/spring-projects/spring-authorization-server/blob/ce76f5c23d3e298b8e929a069bcd7470dfcb6d10/oauth2-authorization-server/src/main/java/org/springframework/security/oauth2/server/authorization/web/OAuth2AuthorizationEndpointFilter.java#L187) and your authentication sub-system can take control of the account selection process.

**Comment by CoimbraVitor** [comment]
Could you provide an example or resource demonstrating how to implement the prompt functionality? I'm specifically looking for guidance on handling the login prompt parameter.
