### ISSUE TITLE
Client mode cannot read request parameters

### ISSUE THREAD

**Issue by yyyyyyyysssss** [spring-projects/spring-authorization-server#1679]
version:
```
<dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-oauth2-authorization-server</artifactId>
            <version>1.3.1</version>
</dependency>
```

Problem code：
```
static MultiValueMap<String, String> getFormParameters(HttpServletRequest request) {
        Map<String, String[]> parameterMap = request.getParameterMap();
        MultiValueMap<String, String> parameters = new LinkedMultiValueMap();
        parameterMap.forEach((key, values) -> {
            String queryString = StringUtils.hasText(request.getQueryString()) ? request.getQueryString() : "";
            if (!queryString.contains(key) && values.length > 0) {
                String[] var5 = values;
                int var6 = values.length;

                for(int var7 = 0; var7 < var6; ++var7) {
                    String value = var5[var7];
                    parameters.add(key, value);
                }
            }

        });
        return parameters;
    }
```
This code  '!queryString.contains(key)' will result in the parameter never being read

**Comment by yyyyyyyysssss** [comment]
Why is that ‘!queryString.contains(key)’ instead of ‘queryString.contains(key)’

**Comment by yyyyyyyysssss** [comment]
This is my request：http://127.0.0.1:9090/oauth2/token?client_id=32b00b1e89af-90d2e0e46d20ebb92f6c&client_secret=123456&redirect_uri=http://127.0.0.1:8081/oauth2/self/login&grant_type=client_credentials&scope=userInfo+openid

**Comment by jgrandja** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces this issue if you feel this is a genuine bug.

> Why is that ‘!queryString.contains(key)’ instead of ‘queryString.contains(key)’

Requests to the `/oauth2/token` endpoint **MUST** be POST (as per spec) so parameters are read from the body **NOT the query string**.
