### ISSUE TITLE
Support PKI Mutual-TLS client authentication method behind proxy server

### ISSUE THREAD

**Issue by Scarange** [spring-projects/spring-authorization-server#1684]
**Expected Behavior**
Support PKI Mutual-TLS client authentication method behind proxy server e.g. nginx, traefik etc.

**Current Behavior**
current implement in `X509ClientCertificateAuthenticationConverter` get end user certificate chain like this:
```
public Authentication convert(HttpServletRequest request) {
	X509Certificate[] clientCertificateChain = (X509Certificate[]) request
			.getAttribute("jakarta.servlet.request.X509Certificate");
	if (clientCertificateChain == null || clientCertificateChain.length == 0) {
		return null;
	}
}
```
it works when end user access AS direct, but AS behind a proxy server e.g. nginx it can't get certification chain. i noticed the [keyclock](https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/services/x509/NginxProxySslClientCertificateLookup.java) has an adaptation for this problem, does AS need a new converter to support it?

Or maybe i made a mistake, somebody can help me how to config AS should worked beind a proxy server.

my nginx config like this:
```
server {
        listen       443 ssl;
        server_name  localhost;

        ssl_certificate             ssl/server.pem;
        ssl_certificate_key         ssl/server.key;
        ssl_protocols               TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers                 AES128-SHA:AES256-SHA:RC4-SHA:DES-CBC3-SHA:RC4-MD5;
        ssl_prefer_server_ciphers   on;
        ssl_session_cache           shared:SSL:10m;
        ssl_session_timeout         10m;
        ssl_verify_client           optional_no_ca;
        ssl_verify_depth            2;

        location / {
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-SSL-CERT $ssl_client_escaped_cert;
            proxy_redirect off;
            client_max_body_size       1000m;
            
            # root   html;
            # index  index.html index.htm;
            proxy_pass http://127.0.0.1:8080;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }

    }
```
**Context**
For production environment, authentication services are usually deployed behind nginx

**Comment by jgrandja** [comment]
@Scarange 

Questions are better suited to [Stack Overflow](https://stackoverflow.com/). We prefer to use GitHub issues only for bugs and enhancements.

> i noticed the keyclock has an adaptation for this problem, does AS need a new converter to support it?

The Keycloak implementation `NginxProxySslClientCertificateLookup` is a custom implementation that we wouldn't add to Spring Authorization Server since it's non-standard. You would have to supply your own implementation similar to `NginxProxySslClientCertificateLookup` that adds the client certificate to an HTTP header and then you would configure a custom `AuthenticationConverter` via `OAuth2AuthorizationServerConfigurer.clientAuthentication().authenticationConverter()` that looks very similar to `X509ClientCertificateAuthenticationConverter` but reads the client certificate from the header instead.

**Comment by Scarange** [comment]
ok, thanks such quick response!
