### ISSUE TITLE
OAuth2AuthorizationEndpointFilter still get SecurityContext from HttpSessionSecurityContextRepository with  expired session(actually expired by SessionInformation)  when Configuring Concurrent Session Control

### ISSUE THREAD

**Issue by Been24** [spring-projects/spring-authorization-server#1841]
**Expected Behavior**
when Configure Concurrent Session Control in OAuth2AuthorizationServerSecurityFilterChain,OAuth2AuthorizationEndpointFilter should load SecurityContext from HttpSessionSecurityContextRepository exclude  session that expired by org.springframework.security.core.session.SessionInformation with EXPIRED_ATTR

**Current Behavior**
In normal SecurityFilterChain,ConcurrentSessionFilter is going to Expired - abort processing such as doLogout;However Due to  OAuth2AuthorizationEndpointFilter is orded before ConcurrentSessionFilter,so it not worked

**Context**

maybe we need a special SecurityContextRepository to do this  in OAuth2AuthorizationServerSecurityFilterChain? or anything other else? hope to receive your help!

**Comment by jgrandja** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/questions/tagged/spring-authorization-server). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces this issue if you feel this is a genuine bug.
