### ISSUE TITLE
Seperate JWT Token generation

### ISSUE THREAD

**Issue by GrmpfNarf** [spring-projects/spring-authorization-server#414]
**Expected Behavior**
It would be nice when the JWT Token generation from ``OAuth2ClientCredentialsAuthenticationProvider`` and ``OAuth2AuthorizationCodeAuthenticationProvider`` is moved to a sperate class so I can reuse it e.g. for an custom AuthenticationProvider
**Current Behavior**
Currently the JWT Token generation for the Access Token is inside the ``authenticate`` method of the both classes. To use it in a custom Authenticationprovider I have to copy the logic and everything around e.g. the ``JwtUtil`` and the resolve of the JwtEncoder from ``OAuth2ConfigurerUtils.getJwtEncoder(builder)``

**Context**
I'm adding a custom Grant Type by adding a converter to the tokenEndpoint which provides an custom AutenticationToken which will be resolved by the custom AuthenticationProvider.

**Comment by jgrandja** [comment]
Thanks for the report @GrmpfNarf.

Hiding the `Jwt` token generation in the `AuthenticationProvider`'s was intentional. However, the plan is to introduce an interface, e.g. `OAuth2TokenIssuer`, which can support any type of token. We'll soon be introducing opaque token support which will trigger some re-factoring.

Rest assured, the `Jwt` token generation will be extracted into a re-useable component, we're just not there yet.

I'll assign this to `0.2.1` but it may get pushed to a later release.

**Comment by denis111** [comment]
The same happens to me, I had to copy-paste `JwtUtil` besides it seems that `JoseHeader` needs to be public because `JwtUtil` returns `JoseHeader.Builder` if you call `JwtUtils.headers()` that is needed to call then `JwtEncodingContext.with(headersBuilder, claimsBuilder)`.  But I see that conflicting class `JoseHeader` in Spring Security 5.6 is not public! So to make any custom Provider we `JoseHeader` to be public or maybe the future refactoring will not require it?

**Comment by erised** [comment]
Hi @jgrandja.
May I take this up if it is not already assigned to anyone ?

**Comment by jgrandja** [comment]
@erised Let me get back to you next week. I'm playing catch up this week :)

**Comment by jgrandja** [comment]
@erised gh-493 and gh-571 are available. Do any of these interest you?

**Comment by erised** [comment]
Hi @jgrandja. Sure. I can work on [gh-493](https://github.com/spring-projects/spring-authorization-server/issues/493).

**Comment by jgrandja** [comment]
@erised Can you comment in gh-493, e.g. "I would like to take this one" so I can assign it to you.
