### ISSUE TITLE
Make OAuth2AuthorizationConsent customizable

### ISSUE THREAD

**Issue by fwollsch** [spring-projects/spring-authorization-server#436]
**Expected Behavior**
When sending additional parameters from a consent-form, these additional parameters should by accessable by User-Code.
The OAuth2AuthorizationConsent should be customizable by a user-definable component before being passed to the OAuth2AuthorizationService.

**Current Behavior**
When sending additional parameters from a consent-form, these additional parameters are present inside the OAuth2AuthorizationCodeRequestAuthenticationToken.
The OAuth2AuthorizationConsent is created only using the authorized scopes.

**Context**
In my OAuth2-Server, a user can create multiple entities.
On the consent-page, the user can review all requested scopes and select which of its entities the client should be given access to.

My consent-page HTML looks like this:
```html
<form method="post" th:action="@{/oauth2/authorize}">
    <input type="hidden" name="client_id" th:value="${clientId}" />
    <input type="hidden" name="state" th:value="${state}" />

    <div th:each="entity : ${entities}">
        <p>
            <input type="checkbox" th:name="${'entity:' + entity.id}" th:text="${entity.displayName}" checked />
        </p>
    </div>

    <hr />

    <div th:each="scope : ${scopes}">
        <input type="hidden" name="scope" th:value="${scope}" />
        <p th:text="${scope}"></p>
    </div>

    <button type="submit">Submit</button>
    <!--<button type="reset">Cancel</button>-->
</form>
```

I need some way to know which entities have been selected by the user on the consent-page.
In my case, all selected entity-ids are present in the OAuth2AuthorizationCodeRequestAuthenticationToken.getAdditionalParameters(), but these are never passed to any User-Code.

Ideally, I'd like to customize the OAuth2AuthorizationConsent before it's being passed to the OAuth2AuthorizationService with access to the additional parameters.

As a workaround, I currently use a custom OAuth2AuthorizationCodeRequestAuthenticationProvider:

```java
    private static final ThreadLocal<Map<String, Object>> ADDITIONAL_PARAMETERS = new ThreadLocal<>();

    public CustomOAuth2AuthorizationCodeRequestAuthenticationProvider(RegisteredClientRepository registeredClientRepository, OAuth2AuthorizationService authorizationService, OAuth2AuthorizationConsentService authorizationConsentService) {
        super(registeredClientRepository, authorizationService, authorizationConsentService);
    }

    @Override
    public Authentication authenticate(Authentication authentication) throws AuthenticationException {
        final OAuth2AuthorizationCodeRequestAuthenticationToken authorizationCodeRequestAuthentication = (OAuth2AuthorizationCodeRequestAuthenticationToken) authentication;
        final Map<String, Object> additionalParameters = authorizationCodeRequestAuthentication.getAdditionalParameters();

        ADDITIONAL_PARAMETERS.set(additionalParameters);
        try {
            return super.authenticate(authorizationCodeRequestAuthentication);
        } finally {
            ADDITIONAL_PARAMETERS.remove();
        }
    }

    public static <T> T getAdditionalParameter(String key) {
        final Map<String, Object> additionalParameters = ADDITIONAL_PARAMETERS.get();
        if (additionalParameters == null) {
            throw new IllegalStateException();
        }

        return (T) additionalParameters.get(key);
    }
```

**Side Nodes**
The additionalParameters are currently created by passing all Request-Parameters that are not explicitly known (such as scope, client_id and state), but only the first value is actually added to the additionalParameters.

This requires my consent-page to send each selected entity using a different name (like in the example HTML above).
Ideally, I would like to use one name (for example "entity") and send the selected entities with their id as a value (like it works with scope at the moment).

**Comment by jgrandja** [comment]
Thanks for the report @fwollsch.

I understand that you're looking to customize the `OAuth2AuthorizationConsent` using input from `OAuth2AuthorizationCodeRequestAuthenticationToken`. Is my understanding correct?

**Comment by fwollsch** [comment]
Hello @jgrandja ,

yes, exactly.

In my case it's the `OAuth2AuthorizationCodeRequestAuthenticationToken#getAdditionalParameters()` which contains all not explicitly mapped Parameters sent the `POST /oauth2/authorize`.

It doesn't have to be the `OAuth2AuthorizationConsentService` which receives these parameters. It can be a entirely new type of Component, if that fits the design better. It's just that *currently* the `OAuth2AuthorizationCodeRequestAuthenticationToken#getAdditionalParameters()` are never passed down to any plugin-able component (that's also because I had to implement it the "hacky" way I showed above).

I attached a video of how my consent page looks like:
https://user-images.githubusercontent.com/72974593/134470267-ba3df5f2-4d16-4e0a-8c6a-2ddc609f332d.mov

This may help to understand what I'm referring to.

**Comment by jgrandja** [comment]
This makes sense @fwollsch.

I was expecting to introduce a `Customizer` component for `OAuth2AuthorizationConsent` at some point. It's very common to have different types of authority information presented to the user during consent, other than `scope`.

I will get to this shortly and propose a design that you can review and validate.

**Comment by markhobson** [comment]
Hi, I've just absorbed this change whilst testing 0.2.1 for another issue. I'm not using this customisation but my deny consent flow now breaks. This is due to [the change in OAuth2AuthorizationCodeRequestAuthenticationProvider](https://github.com/spring-projects/spring-authorization-server/commit/4ce999c01498d13c1c4c4580fd18b19a339eb485#diff-c9b8470e58b8678be868d91539ca2b6ee1033f6d2143849e2051e8d135722adfL304) that now requires no additional parameters to be sent in order to return access denied.

In my case, I'm happening to also submit a CSRF token `_csrf` and the deny button's name `deny`. I could look to remove these but I was wondering what the rationale is for this strict check? If I remove the no additional parameters check then no unit tests fail, which makes me wonder if this is a necessary use case?

**Comment by sjohnr** [comment]
Hi @markhobson. Thanks for bringing it up.

This is a bit tricky, because this feature of adding support for custom authorization consent is essentially making authorized scopes not required, which per the spec, they are not. Therefore, we are looking for either scopes or some additional parameters to be present to determine whether to process the request as a consent. I don't know of any other signal we can look for to continue to support the deny consent flow. I could be wrong, but I think for consistency with your use case, the deny consent flow would have to submit the form without any parameters. If the CSRF token is also present as a form parameter, that might present a real problem with this approach, as I would think a CSRF token should be required when submitting authorization consent.

We'll have to discuss this a bit more and see what options there are for this.

**Comment by jgrandja** [comment]
Thanks for the report @markhobson. We'll address this before we release `0.2.1` next week.

**Comment by jgrandja** [comment]
Thanks again @markhobson for catching this regression before the release next week.

This should not be resolved via c418306.

Can you please confirm the fix has restored original behaviour for your deny consent flow?

**Comment by markhobson** [comment]
Hi @sjohnr @jgrandja, thanks for the replies and the quick fix. I've tried `main` and the deny consent flow now works correctly. Thank you!

**Comment by jgrandja** [comment]
Excellent ! Thanks for checking!

**Comment by manjukas** [comment]
Was this change reversed? Looks like OAuth2AuthorizationConsentContext.java was removed. I got around to implementing the same requirement by adding a consent customizer and getting the parameters from the consent page using the RequestContextHolder. But wondering if another mechanism was provided.
