### ISSUE TITLE
Make redirectUri optional in RegisteredClient

### ISSUE THREAD

**Issue by wsaca** [spring-projects/spring-authorization-server#445]
**Expected Behavior**
RegisteredClient created with an empty redirectUris collection.

**Current Behavior**
RegisteredClient builder throws an error if authorization_code grant is specified and no redirectUri is added.

**Context**
I'm trying to create a RegisteredClient inside a custom JPA RegisteredClientRepository with optional redirect URI. If the RegisteredClient has an empty redirectUris collection the client request shouldn't match and it would be rejected. Actually, the alternative used is to add and empty string to avoid the exception.

**Comment by sjohnr** [comment]
Hi @wsaca, thanks for opening this (related #440).

I'd like a little more info on this one. What is the context under which an empty collection of redirect uris would be present (in the database) such that you need to create a `RegisteredClient` with no redirect uris? Further, what would be the value of having that `RegisteredClient` around so that it can reject all attempts to authenticate using it?

**Note** that the same thing would happen if the database column was null for the `JdbcRegisteredClientRepository`, and even a custom JPA implementation would need to be consistent with the JDBC one (call it a reference implementation).

**Comment by wsaca** [comment]
> What is the context under which an empty collection of redirect uris would be present (in the database) such that you need to create a RegisteredClient with no redirect uris?

Now we can create a `RegisteredClient` with multiple grants, but the redirect URI is not mandatory for all of them. The related database column in `JdbcRegisteredClientRepository` is nullable because its only required by the Authorization Code grant. The reason is to make easier the UI implementation avoiding to remember the relation between one specific grant and the redirect URI.

> Further, what would be the value of having that RegisteredClient around so that it can reject all attempts to authenticate using it?

The request could also be rejected if the user add a wrong URI in the UI, but this adds more freedom of customization without add bad funcionality. At some point the other asserts included in `RegisteredClient` could also be previously validated by the API to display the right error messages in the frontend.

**Comment by sjohnr** [comment]
@wsaca, thanks for the response.

> The reason is to make easier the UI implementation avoiding to remember the relation between one specific grant and the redirect URI.

That definitely makes sense as an application concern. However, I'm not sure the framework should be changed to accommodate that type of downstream requirement. At some point prior to loading the data into Spring Authorization Server, I would expect the application to validate it and provide the end-user with a good experience around fixing the issue. That would be the responsibility of the application or product, as the framework is not providing user experience.

Since this framework is targeted to developers, I believe this change would result in a tradeoff against the developer experience associated with quickly finding and fixing the issue. With that in mind, I'm going to close this issue for now. If you have further thoughts, feel free to add them and we can re-open if needed.
