### ISSUE TITLE
Federated authentication using external identity providers

### ISSUE THREAD

**Issue by metacubed** [spring-projects/spring-authorization-server#462]
Is it possible to configure the Spring Authorization Server to delegate authentication to an external identity provider?

When configured, the "/login" endpoint of the Spring Authorization Server would serve a page showing various login options:

- `[ Log in using a local user ]`
  - _`[ username ]`_
  - _`[ password ]`_
- `[ Log in using <Company> SSO ]`
- `[ Log in using Google ]`

Identity federation may be done using various protocols such as OIDC, SAML, LDAP, etc.
This also includes "Social Login", which is usually a special case of OIDC federation.

Consider adding documentation/samples that show how to implement this using Spring Authorization Server.

**Comment by jgrandja** [comment]
@metacubed Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). We prefer to use GitHub issues only for bugs and enhancements.

The quick answer is Yes, it is possible to configure multiple identity providers in order to federate authentication. However, this is a Spring Security concern, not Spring Authorization Server. You would use Spring Security to configure one or more `AuthenticationProvider`'s.

The Spring Authorization Server sample configures [formLogin()](https://github.com/spring-projects/spring-authorization-server/blob/7680505eedc2116d012f0f3598361a84e2a31c9d/samples/boot/oauth2-integration/authorizationserver/src/main/java/sample/config/DefaultSecurityConfig.java#L43) for the authentication mechanism. You would need to provide a custom security configuration that configures `AuthenticationProvider`'s (SAML, LDAP, OIDC, etc.) with a custom login page for triggering the configured authentication mechanisms.
