### ISSUE TITLE
How to select the value of 'alg' header based on the JWKSource?

### ISSUE THREAD

**Issue by haroldjcastillo** [spring-projects/spring-authorization-server#487]
**Describe the bug**
I'm trying to change the `JWKSet`, instead of using `Jwks.generateRsa()` I want use `Jwks.generateEc()` but throws and exception `org.springframework.security.oauth2.jwt.JwtEncodingException: An error occurred while attempting to encode the Jwt: Failed to select a JWK signing key`

**To Reproduce**
Change the key of the bean `jwkSource()` to `ECKey rsaKey = Jwks.generateEc();`

````sh
curl --request POST \
  --url http://auth-server:9000/oauth2/token \
  --header 'Authorization: Basic bWVzc2FnaW5nLWNsaWVudDpzZWNyZXQ=' \
  --header 'Content-Type: application/x-www-form-urlencoded' \
  --data grant_type=client_credentials
````

**Expected behavior**
Update the JWT header with the selected source

**Sample**
````java
@Bean
  public JWKSource<SecurityContext> jwkSource() {
    ECKey key = Jwks.generateEc();
    JWKSet jwkSet = new JWKSet(key);
    return (jwkSelector, securityContext) -> jwkSelector.select(jwkSet);
  }
````
Or, what's the way to modify the header `alg`?

Thanks, and excellent work!

**Comment by Blackmail92** [comment]
There is a way to get over that problem - this bean works for me:
```
@Bean
OAuth2TokenCustomizer<JwtEncodingContext> jwtCustomizer() {
    return context -> context.getHeaders().algorithm(KeyGeneratorUtils.ESAlgorythm.ES256K);
}
```
Hope this helps!

**Comment by haroldjcastillo** [comment]
@Blackmail92 Thanks, it's a good solution though, isn't it better if JWKSource can auto-detect the algorithm without creating that bean?

**Comment by Blackmail92** [comment]
@haroldjcastillo Well, it;s just a temporary workaround, until there would be a better way :) For now it does help with that issue, hope that sooner or later it wll be fixed)

**Comment by sjohnr** [comment]
Thanks @Blackmail92 for the workaround! Unfortunately, this isn't at the top of my list yet, but I'll circle back to it asap.

**Comment by jgrandja** [comment]
@haroldjcastillo 

> isn't it better if JWKSource can auto-detect the algorithm without creating that bean?

In a production deployment, it is highly likely that `JWKSource` will contain more than one key. There could be 2 active signing keys (RSA and EC) and 2 passive keys (RSA and EC). In this scenario, there is no way to deduce the correct `alg` to default for the `JoseHeader`.

Furthermore, a key can only be selected using attributes of the `JoseHeader`. A common selection strategy is using the `alg`or `kid` from the `JoseHeader` to select the correct key in `JWKSource`.

If you need to select a specific key from `JWKSource`, then you can set the appropriate header(s) in `JoseHeader` via `OAuth2TokenCustomizer` as commented by @Blackmail92. The intended design of `OAuth2TokenCustomizer` is to customize the headers and/or claims.

For future reference, questions are better suited to [Stack Overflow](https://stackoverflow.com/). We prefer to use GitHub issues only for bugs and enhancements.

**Comment by Blackmail92** [comment]
There is one problem. @jgrandja @sjohnr  Really sorry for tag, but there is a small issue with this workaround, probably you could help with it. Problem is - when I use the ECDSA key with the secp256k1 curve (alg=ES256K), and customise the header as I provided above, when a resource server checks the token, it cant find the required alg, because jwsAlgorythms in `JWSVerificationKeySelector` list includes only ES256, ES384 and ES512, so it fails with the "Signed JWT rejected: Another algorithm expected, or no matching key(s) found" error.

What makes me a bit confused, is a fact that the check works perfectly fine when we use same app as AuthServer and Resource servar simultaneously. I guess some beans from auth server let us do that.. Is there any way to add some values to the supported algs list in the `JWSVerificationKeySelector` ?

**Comment by sjohnr** [comment]
Hi @Blackmail92, I understand you're working on getting the key selector functionality to use your desired algorithm. This feels like a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it). We will try and take a look at it, but if you can add a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) demonstrating what you're trying to get working, that would be very helpful.
