### ISSUE TITLE
OAuth2AccessTokenAuthenticationToken authorities

### ISSUE THREAD

**Issue by mensa23** [spring-projects/spring-authorization-server#548]
Why OAuth2AccessTokenAuthenticationToken's authorities is Collections.emptyList()?

Any method can setAuthorities in OAuth2AccessTokenAuthenticationToken?

Source Code:
https://github.com/spring-projects/spring-authorization-server/blob/main/oauth2-authorization-server/src/main/java/org/springframework/security/oauth2/server/authorization/authentication/OAuth2AccessTokenAuthenticationToken.java

**Comment by sjohnr** [comment]
Hi @mensa23. Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces this issue if you feel this is a genuine bug.

I'm going to close this for now. But feel free to let me know if I've misunderstood something.
