### ISSUE TITLE
OAUTH2 WithIn Application

### ISSUE THREAD

**Issue by dilipdhankecha** [spring-projects/spring-authorization-server#584]
If we have spring authorization oauth2 server, now we want to implement it within our application but the problem is we need to redirect user with redirect uri.
if we want to generate accesstoken and refreshtoken with the help of username and password is this possible with the help of spring authorization server?

**Comment by sjohnr** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it).
