### ISSUE TITLE
Can give some suggestion or samples for restapi login without web form and social login ?

### ISSUE THREAD

**Issue by ktiot** [spring-projects/spring-authorization-server#585]
Is this project target for all of login&authorization solution and how this project fix position above gateway
I want always study login again and again integration 
I hope so this is the last project !

**Comment by sjohnr** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it).
