### ISSUE TITLE
difrrent RegisteredClient has the same clientId and different id, it will get the wrong client when request /oauth2/token

### ISSUE THREAD

**Issue by MODjie** [spring-projects/spring-authorization-server#599]
when we config RegisteredClientRepository, if RegisteredClient with a random id , and clientId keep the same all the time. every time start up the application, it will insert a new client record into client table, it will produce multi record has the same clientId. when we request the uri "/oauth2/token" to get token , "OAuth2AuthorizationCodeRequestAuthenticationProvider.authenticateAuthorizationRequest" use clientId to find a record, so it will the wrong record.
![image](https://user-images.githubusercontent.com/22852105/150511415-e26eb114-0fd3-4157-bce0-3fd3123fb81b.png)
![image](https://user-images.githubusercontent.com/22852105/150511347-d3ced517-8ec7-489f-9fb1-5c1a5258882d.png)

**Comment by sjohnr** [comment]
@MODjie, thanks for your interest in the project.

The sample included in this repository loads a record into the database on startup because it is using an h2 in-memory database for demonstration purposes only. Your application should not do this, as your database is likely persistent. You should initialize and load data in a way that is not tied to the startup of the application.

Since this is due to incorrect configuration/setup, I'm going to close this issue for now. If I've misunderstood anything, please let me know and we can re-open this issue if necessary to discuss further.
