### ISSUE TITLE
Add possibility to specify a default scope value for authorization requests

### ISSUE THREAD

**Issue by sjaeger-lxo** [spring-projects/spring-authorization-server#600]
**Expected Behavior**
RFC says: "If the client omits the scope parameter when requesting authorization, the authorization server MUST either process the request using a pre-defined default value or fail the request indicating an invalid scope."
https://datatracker.ietf.org/doc/html/rfc6749#section-3.3
Also referenced here for Authorization Request: https://datatracker.ietf.org/doc/html/rfc6749#section-4.1.1

**Current Behavior**
If the scope parameter is empty or omitted, then the consent page is presented with no scopes.
Having a connection without any permissions seems pointless.

**Context**
I'd like to implement the behavior that when no scopes are submitted by the client, then all scopes from the registered client should be add to the authorization request and thus presented on the consent page to the user.
I looked up the code a bit and found that in class `OAuth2AuthorizationCodeRequestAuthenticationConverter` the scopes are extracted into `OAuth2AuthorizationCodeRequestAuthenticationToken` which is used in further processing.
Unfortunately, I cannot modify `OAuth2AuthorizationCodeRequestAuthenticationConverter` without complete copy code because the class is final.
It would be great to be able to specify a default other than null.

**Comment by jgrandja** [comment]
@sjaeger-lxo I'd like to understand your use case more:

> I'd like to implement the behavior that when no scopes are submitted by the client

Why would the client not request any scope(s)?

**Comment by sjaeger-lxo** [comment]
@jgrandja 

> Why would the client not request any scope(s)?

Basically, such a behavior can be seen as a convenience feature when the client does not have to provide any of his registered scopes 
because the client always wants all its scopes which are specified in the client details.
The user's consent is still required at the approval step during the auth flow.


In my company's specific case, we provide a rest api to our business partners and manage the oauth2 clients for them. That means public registration ist not possible.
For every client we specifiy only the set of scopes that they need.

**Comment by jgrandja** [comment]
@sjaeger-lxo Thanks for the explanation.

This is non-standard behaviour and needs to be implemented in the consuming application.

You will need to supply a custom `AuthenticationConverter` via:

```java
authorizationServerConfigurer
		.authorizationEndpoint(authorizationEndpoint ->
				authorizationEndpoint
						.authorizationRequestConverter(customAuthorizationRequestConverter()));
```

...and you can use a delegation-based strategy:

```java
private AuthenticationConverter customAuthorizationRequestConverter() {
	final OAuth2AuthorizationCodeRequestAuthenticationConverter delegate =
			new OAuth2AuthorizationCodeRequestAuthenticationConverter();
	return (request) -> {
		OAuth2AuthorizationCodeRequestAuthenticationToken authorizationCodeRequestAuthentication =
				(OAuth2AuthorizationCodeRequestAuthenticationToken) delegate.convert(request);

		// TODO Lookup RegisteredClient using RegisteredClientRepository.findByClientId(authorizationCodeRequestAuthentication.getClientId())

		// TODO Return a copy of authorizationCodeRequestAuthentication with the updated scopes

		return authorizationCodeRequestAuthentication;
	};
}
```

I'm going to close this as custom behaviour needs to be implemented in the application.

**Comment by jgrandja** [comment]
@mikesaurus I agree with your points. We will address this in gh-780. If you have additional comments, please add it there.

**Comment by lucwillems** [comment]
i agree that behaviour should be similar is all grant types but which one, defaulting to client configured scopes or empty set.
as @sjaeger-lxo  mentioned it makes configuration for a lot of clients simpler and easier to manage.

both behaviours are valid so why not let us choose the response on empty request scopes.

when consent flow is used, the scope set is a subset of the determinant by the users consent response. in most cases this will be all scopes  configured to the client, but the user can reduce this set to nothing.

When "auto" consent , aka requireAuthorizationConsent(false) , we don't ask the user about what scopes are allowed, 
but than we (the administrator/programmer/...) need to determine what is the correct usage of scopes. 

Note that we do not always have access to configurations of the application which is using the client id , is B2B cases this is an external administrator that needs todo do reconfiguration when scopes change or need to be adopted , possible breaking the flow until configuration is finished.

using Delegated AuthenticationConverter is not really  a good options here. there is no reason to change request input parameters by replacing them by the client scope set incase there missing or empty in the request. 

This will lead to misunderstanding because request input and handling of this input  != the request the client actually send. 
the state of the request is stored in an modified way which could hinder audit and other check on the data.

**Comment by mikesaurus** [comment]
@lucwillems I think that the point of defaulting to an empty scope set is that Spring should not presume to know the business and/or security processes and requirements for any implementing application and should therefore not presume to set a default scope value in response to the case where the client does not request scope. Additionally, assuming that any request without scope should include a scope value in the response violates the principal of "least privilege", especially in the case where user consent is bypassed. IMO, Spring's default behavior should be as secure/restrictive as possible while providing the ability for implementing applications to customize the process if they want it to be less secure/restrictive.

**Comment by mikesaurus** [comment]
@lucwillems Also, if you consider it from another perspective, the default empty scope set makes every request intuitive and transparent because the scope in the response == the scope in the request, without modification or having to explain the behavior.
