### ISSUE TITLE
UserDetails not validated on refresh token

### ISSUE THREAD

**Issue by SavchenkoVV** [spring-projects/spring-authorization-server#603]
**Describe the bug**
UserDetails not validated on refresh token. Refresh token possible for removed or blocked users.

**To Reproduce**
1. Auth by user and get access and refresh token
2. Remove or block user
3. Make refresh token. It will success

**Expected behavior**
Need validate UserDetails on refresh token

**Comment by sjohnr** [comment]
@SavchenkoVV thanks for your interest in the project!

Can you please say more about why you believe this is a bug (instead of an enhancement)? For example, do you have in mind anything in the OAuth 2.1 specification that aligns with your desired behavior?

This would also be possible to implement as a customization, by providing your own wrapper implementation of `OAuth2AuthorizationService` that delegates to another implementation, and uses `UserDetailsService` to validate the principal on the return value. For example:

```java
public class UserDetailsOAuth2AuthorizationService implements OAuth2AuthorizationService {
    private final OAuth2AuthorizationService delegate;
    private final UserDetailsService userDetailsService;

    public UserDetailsOAuth2AuthorizationService(OAuth2AuthorizationService delegate, UserDetailsService userDetailsService) {
        this.delegate = delegate;
        this.userDetailsService = userDetailsService;
    }

    @Override
    public OAuth2Authorization findById(String id) {
        OAuth2Authorization authorization = this.delegate.findById(id);
        if (authorization != null) {
            UserDetails userDetails = this.userDetailsService.loadUserByUsername(authorization.getPrincipalName());
            if (!userDetails.isEnabled()) {
                throw new OAuth2AuthenticationException(OAuth2ErrorCodes.INVALID_REQUEST); // or your own error
            }
            /* Other validations... */
        }
        return authorization;
    }

    /* Other methods... */
}
```

**Comment by SavchenkoVV** [comment]
Sorry, but i thinks it is base of security for authorization server.
Now, by default, it is not possible to block user who has refresh_token. For example, after leak.

Of cource specifiation can be understaned differently, but it of literally stuffing with security notes. 
I think it is not accepteable to authenticate removed or blocked user for authorization server by any reason.

**Comment by sjohnr** [comment]
Thanks @SavchenkoVV, I think I am understanding where you're coming from.

Unfortunately, integrating this type of check with `UserDetails` / `UserDetailsService` would tie the validation to a specific way of looking up users. The `UserDetailsService` is meant to be used by certain types of authentication (for example, the `DaoAuthenticationProvider` used by form login). But there are many types of authentication, not all of which use `UserDetailsService` or produce a `UserDetails`.

Since it's possible to do something like this (see above example), I think this would be better as an enhancement suggestion, but it would need to be less specific. For example, it could be valuable to add a mechanism to plug in a validator for the `OAuth2Authorization` prior to authenticating a refresh token. This would allow implementations to validate any type of `Principal`, not just a `UserDetails`.

I'll leave this open for more discussion and will take this away to think about it. But I think I'd prefer to open a more general enhancement for this issue.

**Comment by SavchenkoVV** [comment]
Thanks, @sjohnr. 

In spring-security-oauth2 it was via AuthenticationManager
```
OAuth2Authentication authentication = this.tokenStore.readAuthenticationForRefreshToken(refreshToken);
if (this.authenticationManager != null && !authentication.isClientOnly()) {
    Authentication userAuthentication = authentication.getUserAuthentication();
    PreAuthenticatedAuthenticationToken preAuthenticatedToken = new PreAuthenticatedAuthenticationToken(userAuthentication, "", authentication.getAuthorities());
    if (userAuthentication.getDetails() != null) {
        preAuthenticatedToken.setDetails(userAuthentication.getDetails());
    }

    Authentication user = this.authenticationManager.authenticate(preAuthenticatedToken);
    Object details = authentication.getDetails();
    authentication = new OAuth2Authentication(authentication.getOAuth2Request(), user);
    authentication.setDetails(details);
}
```

**Comment by sjohnr** [comment]
@SavchenkoVV, that is a good point. It would be possible to also plug in a custom `AuthenticationProvider`. I think it would accept a `OAuth2RefreshTokenAuthenticationToken` and delegate to the existing `OAuth2RefreshTokenAuthenticationProvider` upon successfully validating the user. Something like:

```java
public class UserDetailsRefreshTokenAuthenticationProvider implements AuthenticationProvider {
    private final OAuth2RefreshTokenAuthenticationProvider delegate;
    private final UserDetailsService userDetailsService;
    private final OAuth2AuthorizationService authorizationService;

    public UserDetailsRefreshTokenAuthenticationProvider(OAuth2RefreshTokenAuthenticationProvider delegate, UserDetailsService userDetailsService, OAuth2AuthorizationService authorizationService) {
        this.delegate = delegate;
        this.userDetailsService = userDetailsService;
        this.authorizationService = authorizationService;
    }

    @Override
    public boolean supports(Class<?> authentication) {
        return OAuth2RefreshTokenAuthenticationToken.class.isAssignableFrom(authentication);
    }

    @Override
    public Authentication authenticate(Authentication authentication) throws AuthenticationException {
        OAuth2RefreshTokenAuthenticationToken refreshTokenAuthentication =
            (OAuth2RefreshTokenAuthenticationToken) authentication;

        OAuth2Authorization authorization = this.authorizationService.findByToken(
            refreshTokenAuthentication.getRefreshToken(), OAuth2TokenType.REFRESH_TOKEN);

        if (authorization != null) {
            UserDetails userDetails = this.userDetailsService.loadUserByUsername(authorization.getPrincipalName());
            if (!userDetails.isEnabled()) {
                throw new OAuth2AuthenticationException(OAuth2ErrorCodes.INVALID_REQUEST); // or your own error
            }
            /* Other validations... */
        }

        return this.delegate.authenticate(authentication);
    }
}
```

I'd have to fiddle with registering this provider to test it out, but that's another possible approach. Still, this would be a customization in your application, and I don't see it being general enough to be in the framework.

**Comment by sjohnr** [comment]
@SavchenkoVV, just checking in. Do you have any feedback on the last comment and the example code I provided?

**Comment by SavchenkoVV** [comment]
@sjohnr Thanks for example. Of cource it solve problem. 
But, i think via main AuthenticationManager(or same) as it was in spring-security-oauth2 will be better.

Still the default behavior should be more secure.
Otherwise, everyone will need to implement a similar provider.
