### ISSUE TITLE
Authorization code flow does not redirect correctly after form login, when setting SessionCreationPolicy to STATELESS.

### ISSUE THREAD

**Issue by natami** [spring-projects/spring-authorization-server#627]
**Describe the bug**
Authorization code flow does not redirect correctly, when setting SessionCreationPolicy to stateless.

`http.sessionManagement().sessionCreationPolicy(SessionCreationPolicy.STATELESS);`

Spring security can not trace my authentication info between login and authorization-code grant behaviour because the info is not retained between two requests.

Is there a way to lookup the state and redirect_uri to ensure proper redirect after submitting login form? - something along the lines of AuthorizationRequestRepository used in oauth2login??

Without relying on Spring session and other alike implementations?

**To Reproduce**

```
@Bean
@Order(Ordered.HIGHEST_PRECEDENCE)
public SecurityFilterChain authorizationServerSecurityFilterChain2(HttpSecurity http) throws Exception {
http.formLogin();
http.sessionManagement().sessionCreationPolicy(SessionCreationPolicy.STATELESS);

OAuth2AuthorizationServerConfiguration.applyDefaultSecurity(http);

return http.build();
}
```

**Expected behavior**
Spring security redirects back to appropriate redirectUri.

**Comment by jgrandja** [comment]
@natami Thanks for getting in touch, but questions are better suited to [Stack Overflow](https://stackoverflow.com/). We prefer to use GitHub issues only for bugs and enhancements.

**Comment by natami** [comment]
@jgrandja : Thanks for responding. I fail to see why this is a question better suited to Stack Overflow?

I'm not sure this is a bug or an enhancement - but the problem is Spring Authorization Server currently requires session support to be able to redirect back to the correct redirectUrl after doing a login.
Enabling Session support in our setup is not an option.

So maybe an enhancemnt request - to make redirect after login work in a stateless application?

**Comment by jgrandja** [comment]
@natami The default configuration for `http.formLogin()` configures a `SavedRequestAwareAuthenticationSuccessHandler` and replays the "Saved Request" (if available) after the user successfully authenticates. However, setting `http.sessionManagement().sessionCreationPolicy(SessionCreationPolicy.STATELESS)` disables sessions and the (originally) "Saved Authorization Request" is not saved to session and therefore is not replayed as it is in the default configuration.

This is not a Spring Authorization Server issue and instead a Spring Security configuration issue since the settings are specific to `http.sessionManagement()` and `http.formLogin()`.

**Comment by natami** [comment]
@jgrandja : Thanks for explaining,
