### ISSUE TITLE
There is no ability to set authenticationDetailsSource OAuth2TokenEndpointFilter

### ISSUE THREAD

**Issue by bostandyksoft** [spring-projects/spring-authorization-server#629]
**Expected Behavior**
OAuth2TokenEndpointConfigurer provdes some way to override authenticationDetailsSource of OAuth2TokenEndpointFilter

**Current Behavior**
OAuth2TokenEndpointConfigurer does not provdes any way to override authenticationDetailsSource  of OAuth2TokenEndpointFilter

**Context**
Our project has custom authenticationDetailsSource, but we can't use it. If you will provide way to provide PR i ready to do it

Best regards

**Comment by jgrandja** [comment]
@bostandyksoft It was intentional not to expose `authenticationDetailsSource` via `OAuth2TokenEndpointConfigurer`. Instead, you can register an `ObjectPostProcessor<OAuth2TokenEndpointFilter>` `@Bean`, which will allow you to `OAuth2TokenEndpointFilter.setAuthenticationDetailsSource()`. Please see this [comment](https://github.com/spring-projects/spring-authorization-server/pull/448#discussion_r733982507) for additional details.

**Comment by jgrandja** [comment]
@bostandyksoft Try this:

```java
HttpSecurity.addObjectPostProcessor(tokenEndpointCustomizer());

ObjectPostProcessor<OAuth2TokenEndpointFilter> tokenEndpointCustomizer() {
	return new ObjectPostProcessor<OAuth2TokenEndpointFilter>() {
		@Override
		public <O extends OAuth2TokenEndpointFilter> O postProcess(O tokenEndpointFilter) {
			// TODO
			tokenEndpointFilter.setAuthenticationDetailsSource(null);

			return tokenEndpointFilter;
		}
	};
}
```
