### ISSUE TITLE
Ability to Authenticate Dynamically Registered Clients without using Deprecated Password Encoder

### ISSUE THREAD

**Issue by emyasa** [spring-projects/spring-authorization-server#631]
**Expected Behavior**
To have a non-deprecated password encoder for dynamically registered clients / To have a way to set the password encoding for dynamically registered clients.

**Current Behavior**
When using the connect/register endpoint for dynamic client registration, the clientSecret uses StringKeyGenerator. Thus, when authenticating the said clients, it does not match the use of Password Encoder in general.
![image](https://user-images.githubusercontent.com/70507913/154806389-8dc64912-14dd-41cf-bef6-fdcc7216b06b.png)

**Context**
One workaround I came up with is defining a  NoOpPasswordEncoder bean (using the getInstance static method); however, it's deprecated.
![image](https://user-images.githubusercontent.com/70507913/154806414-5a492be5-7071-412b-b8a0-90b6598f2b7d.png)

I would be pleased to know if I'm missing something or if there's a better alternative than the workaround I'm using. Thanks.

**Comment by lcxw** [comment]
just client.setclientsecret(passwordencoder.encode(you generatekey))

**Comment by emyasa** [comment]
@lcxw Yeah, that'll work as a hard-coded value (or if we're going to have our own implementation of client registration); however, for my requirements I need it to be dynamic, and I'd like to utilize the already provided /connect/register endpoint (OidcClientRegistrationEndpointFilter). 

Thanks by the way, if you think I'm missing something out feel free to expound more.

**Comment by jgrandja** [comment]
@emyasa `OidcClientRegistrationAuthenticationProvider` has been implemented to spec.

In [Section 3.1.  Client Registration Request](https://openid.net/specs/openid-connect-registration-1_0.html#RegistrationRequest), it states:

> To register a new Client at the Authorization Server, the Client sends an HTTP POST message to the Client Registration Endpoint with any Client Metadata parameters that the Client chooses to specify for itself during the registration. The Authorization Server assigns this Client a unique Client Identifier, **optionally assigns a Client Secret**

As you noticed, the `clientSecret` is assigned via `CLIENT_SECRET_GENERATOR`, which is the expected behaviour.

If you require dynamic client registration and the `clientSecret` needs to be encoded, a custom configuration is required to meet those requirements.

Here is a sample custom configuration that works:

Replace the `RegisteredClientRepository` `@Bean` defined in `OidcClientRegistrationTests.AuthorizationServerConfiguration` with:

```java
@Bean
RegisteredClientRepository registeredClientRepository(PasswordEncoder passwordEncoder) {
	RegisteredClient registeredClient = TestRegisteredClients.registeredClient()
			.clientSecret(passwordEncoder.encode("secret"))
			.build();
	RegisteredClientRepository delegate = new InMemoryRegisteredClientRepository(registeredClient);

	return new RegisteredClientRepository() {

		@Override
		public void save(RegisteredClient registeredClient) {
			if (StringUtils.hasText(registeredClient.getClientSecret())) {
				RegisteredClient encodedRegisteredClient = RegisteredClient.from(registeredClient)
						.clientSecret(passwordEncoder.encode(registeredClient.getClientSecret()))
						.build();
				delegate.save(encodedRegisteredClient);
			} else {
				delegate.save(registeredClient);
			}
		}

		@Override
		public RegisteredClient findById(String id) {
			return delegate.findById(id);
		}

		@Override
		public RegisteredClient findByClientId(String clientId) {
			return delegate.findByClientId(clientId);
		}

	};
}
```

**NOTE:** The above sample uses `InMemoryRegisteredClientRepository`, but you can use any `RegisteredClientRepository` implementation for this delegation-based pattern.

And replace the `PasswordEncoder` `@Bean` with:

```java
@Bean
PasswordEncoder passwordEncoder() {
	return PasswordEncoderFactories.createDelegatingPasswordEncoder();
}
```

Now run the test `OidcClientRegistrationTests.requestWhenClientRegistrationRequestAuthorizedThenClientRegistrationResponse()` and you will see the `clientSecret` is encoded for the dynamically registered client.

I'm going to close this as `OidcClientRegistrationAuthenticationProvider` is implemented to spec and the above custom configuration will work for your use case.
