### ISSUE TITLE
Why do '/oauth2/token' endpoints only allow POST requests

### ISSUE THREAD

**Issue by zxiaozhou** [spring-projects/spring-authorization-server#682]
**Describe the bug**
 1. Why do oauth2/token endpoints only allow POST requests.There is also no support for putting data in the body(Isn't a POST request allowed to put data in the body?)；
 2. The trace code finds that initialization forces only POST requests to be matched；
<img width="1507" alt="image" src="https://user-images.githubusercontent.com/62740686/162602725-4fac5569-f5c3-48b0-9580-f2a5ba622dbe.png">

**Comment by sjohnr** [comment]
@zxiaozhou, thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/questions/tagged/spring-security). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it).

For more info on the token endpoint, please see [OAuth 2.1, Section 3.2.2](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-v2-1-05#section-3.2.2).
