### ISSUE TITLE
Jwt assertion client authentication- can we make client ID optional parameter?

### ISSUE THREAD

**Issue by atjohn-csam** [spring-projects/spring-authorization-server#699]
**Expected Behavior**
(https://www.rfc-editor.org/rfc/rfc7523#:~:text=Authentication%20of%20the%20client%20is%20optional%2C)
The spec says the client id is optional, and there are certifications tools out there which will test this workflow as per the spec. Since client ID is optional in the spec, can we consider making it optional in spring implementation as well?

**Current Behavior**
Client ID is mandatory.

**Context**
I had gone through the pull request where JWT profile authentication was implemented and have seen the discussions around making client ID mandatory. I understand the risk of decoding the JWT before verifying the client ID, but can we at least make it configurable so that the user can decide if client ID should be mandatory. Since the spec says it is optional, for me, application is failing the automated testing for certifications. 

Right now as a work around I am creating a custom JWTClientAssertionAuthenticationConverter. Though it works, I am wondering if there are better approaches.

**Comment by atjohn-csam** [comment]
I have one more request one JWT client assertion authentication.

Expected Behavior:
Right now the client assertion is validated on the aud parameter= "token end point" from the provider configuration. Is there ay way I can make a custom token end point with dynamic path variable? Example: http://localhost:1002/oauth/oauth2/token/{customParam}

What I am trying to achieve is that, I would like to receive some additional parameter in case of jwt assertion authentication method, which can be processed separately. 

Current Behavior:
Token end point customization doesnt allow URI template variables in the url.
I tried adding the template variable for token end point but it failed with the following error:
"Caused by: java.net.URISyntaxException: Illegal character in path "


Context:
Can you pls let me know if I can achieve adding path variables to the token end point?

**Comment by jgrandja** [comment]
@atjohn-csam Although the spec [Assertion Framework for OAuth 2.0 Client Authentication and Authorization Grants](https://datatracker.ietf.org/doc/html/rfc7521#section-4.2) states the `client_id` is OPTIONAL, the [JSON Web Token (JWT) Profile for OAuth 2.0 Client Authentication and Authorization Grants](https://datatracker.ietf.org/doc/html/rfc7523) does not specify whether `client_id` is OPTIONAL or REQUIRED.

The primary reason the current implementation requires it, is because we cannot trust a `Jwt` (or any of its headers/claims) until it is verified (signature or decrypted), since this would open up security risks.

The second reason the `client_id` is required is because we need access to the `RegisteredClient` to perform some initial validation of the request in `JwtClientAssertionAuthenticationProvider`. Furthermore, we need to determine where the public key (`registeredClient.getClientSettings().getJwkSetUrl()`) is for the client so the signature can be verified.

`JwtClientAssertionAuthenticationProvider` requires the `client_id` or it will simply fail so I don't see how we can make this optional.

> there are certifications tools out there which will test this workflow

Can you please provide a link to the certification tools that test this? I would like to look into this further.

**Comment by atjohn-csam** [comment]
Thanks for the response @jgrandja 

Providing a certification tool which is used in healthcare: https://inferno.healthit.gov/inferno/

**Comment by jgrandja** [comment]
@atjohn-csam The link you provided is the main link but can you provide a more detailed link on the specific test the certification tool is performing and the results of the test.

**Comment by atjohn-csam** [comment]
Hi @jgrandja, In the inferno website we have to add a resource server url. The tool will act as a client and test with the combination of resource server, authorization server and provide testing results. This is used for certification requirements in health care domain.

Please find below the set of tests inferno does in a screen shot.

![test](https://user-images.githubusercontent.com/87732008/171679344-d348a8bf-b10e-423c-a263-60aecebfa963.JPG)


I registered the inferno tool's jwks uri for one of the registered client and ran the test. While sending the token request, inferno tool did not send the client id as a parameter since it is optional. The tool marked my implementation as failed.

**Comment by jgrandja** [comment]
@atjohn-csam The information you provided still does not provide me with enough information on the details of the conformance testing performed. Also, I never heard of Inferno and looking at the website and GitHub site does not reveal to me the usage/adoption of this conformance testing tool.

As mentioned, in this [comment](https://github.com/spring-projects/spring-authorization-server/issues/699#issuecomment-1111472160):

> `JwtClientAssertionAuthenticationProvider` requires the `client_id` or it will simply fail so I don't see how we can make this optional.

Based on this and the other reasons mentioned in the comment, we cannot make `client_id` optional.

An alternative option you can consider is to provide your own custom implementation of `JwtClientAssertionAuthenticationProvider` and `JwtClientAssertionAuthenticationConverter` and configure it via `authorizationServerConfigurer.clientAuthentication()`. See the [reference documentation](https://docs.spring.io/spring-authorization-server/docs/current/reference/html/configuration-model.html#configuring-client-authentication) on how to configure/extend client authentication.
