### ISSUE TITLE
I need to know an important question.

### ISSUE THREAD

**Issue by lu-cheng** [spring-projects/spring-authorization-server#715]
While I know I should be asking questions on Stack Overflow, I don't think there's an answer to my question there. So sorry to post this kind of question here.

Is this project independent?
Is this project based on a derivative of Spring Security?
Or is Spring Security just the default implementation of the authentication feature for this project?
Because I found that this project has no middle layer of Spring Security and is deeply coupled with Spring Security.
I hope that the above concepts can be clarified, and it will be very helpful for me to think about related issues.

**Comment by sjohnr** [comment]
@lu-cheng as you mentioned, we do prefer to use [Stack Overflow](https://stackoverflow.com/questions/tagged/spring-security) for questions like this.

Take a look at the [Getting Help](https://docs.spring.io/spring-authorization-server/docs/0.3.0-SNAPSHOT/reference/html/getting-help.html) page in our in-progress reference documentation which has answers to your questions and links to learn more. If you have additional questions or need more clarification, feel free to update this issue with a link to an existing or new Stack Overflow question (so that other people can find it).
