### ISSUE TITLE
Refresh token encoding

### ISSUE THREAD

**Issue by k-chandra** [spring-projects/spring-authorization-server#718]
**Expected Behavior**
As per OAuth2.1 specification, the refresh_token can be String / Encoded value.

From https://datatracker.ietf.org/doc/html/draft-ietf-oauth-v2-1-01#section-1.5

"The refresh token may be an identifier used to retrieve the authorization information or may encode this information into the string itself. "

**Current Behavior**
Currently the  org.springframework.security.oauth2.server.authorization.token.JwtGenerator which was introduced in 0.2.3 does not support "refresh_token". 

Would it be possible to add the encoding feature for the refresh_token.

**Comment by sjohnr** [comment]
Hi @k-chandra, thanks for reaching out and welcome to the project!

> As per OAuth2.1 specification, the refresh_token can be String / Encoded value.

While the specification does indeed say that it *may* be an encoded value, it does not seem to specify any additional possibilities for what would be contained and in what situation it would be used. However, you can provide your own `JwtGenerator` which does this, even one that makes use of `JwtEncoder`.

Is there an additional specification you're looking at which requires a JWT `refresh_token`? Otherwise, I'm not sure this would be a feature provided by the framework, but would instead be provided as a customization by the application.

**Comment by k-chandra** [comment]
HI @sjohnr., thank you for providing the details.

In old spring-security-oauth2 server., we used to encode additional claims info into the refresh_token refresh_

> Hi @k-chandra, thanks for reaching out and welcome to the project!
> 
> > As per OAuth2.1 specification, the refresh_token can be String / Encoded value.
> 
> While the specification does indeed say that it _may_ be an encoded value, it does not seem to specify any additional possibilities for what would be contained and in what situation it would be used. However, you can provide your own `OAuth2TokenGenerator` which does this, even one that makes use of `JwtEncoder`.
> 
> Is there an additional specification you're looking at which requires a JWT `refresh_token`? Otherwise, I'm not sure this would be a feature provided by the framework, but would instead be provided as a customization by the application.

**Comment by sjohnr** [comment]
You're quite welcome @k-chandra! I believe you can provide an `OAuth2TokenCustomizer<JwtEncodingContext>`, for example:

```java
@Bean
public OAuth2TokenCustomizer<JwtEncodingContext> tokenCustomizer() {
	return (context) -> {
		if (OAuth2TokenType.ACCESS_TOKEN.equals(context.getTokenType())) {
			context.getClaims().claims((claims) -> {
				claims.put("claim-1", "value-1");
				claims.put("claim-2", "value-2");
			});
		}
	};
}
```

If I'm not mistaken, this would be applied even when issuing an `access_token` in response to the `refresh_token` grant.

**Comment by sjohnr** [comment]
Since there are multiple possible ways to achieve what you're looking for, I'm going to go ahead and close this issue. If there's something that's not possible (with customization) that was possible in the legacy project or I've missed something, feel free to leave additional comments and we can re-open if necessary.
