### ISSUE TITLE
Cannot incrementally approve consent

### ISSUE THREAD

**Issue by markhobson** [spring-projects/spring-authorization-server#734]
**Describe the bug**
Authorizing one or more scopes works correctly when:

1. All scopes are approved
2. Or, all scopes are denied

If scopes are partially approved then the user cannot initiate reauthorization.

**To Reproduce**
This can be reproduced using the "Messages Sample":

1. Authorize the client using authorization code
2. Check "message.read" only and submit consent
4. Attempt to reauthorize the client using authorization code
5. User is **not** prompted to consent to "message.write"

Restarting samples-messages-client and then attempting to reauthorize **does** allow the user to approve further consent.

**Expected behavior**
Attempting to reauthorize the client should allow the user to approve further consent.

**Sample**
See "Messages Sample" with the above instructions.

I believe that the underlying problem here is https://github.com/spring-projects/spring-security/issues/5381. `DefaultOAuth2AuthorizedClientManager.authorize` does not consider whether the already authorized client has all the requested scopes.

When all scopes are approved, short-circuiting authorization makes sense. When all scopes are denied, no authorized client is saved and the authorization process proceeds as new. When scopes are partially approved, any authorized client is deemed suitable and reauthorization does not take place. This leaves the user in a dead-end.

**Comment by jgrandja** [comment]
@markhobson This issue is not related to Spring Authorization Server but instead the client support in Spring Security.

> Restarting samples-messages-client and then attempting to reauthorize does allow the user to approve further consent.

The `DefaultOAuth2AuthorizedClientManager` uses the previously authorized `OAuth2AuthorizedClient` and associated access token to call the protected resource. This is expected default behaviour.

If you need the client to be re-authorized for cases where only a subset of the scopes were authorized then this change needs to be applied in Spring Security client support. An alternative option is to provide your own implementation of `OAuth2AuthorizedClientManager` and/or `OAuth2AuthorizedClientRepository` with this custom behaviour.
