### ISSUE TITLE
Add the possibility to add at_hash claim to ID Token

### ISSUE THREAD

**Issue by pixel13** [spring-projects/spring-authorization-server#744]
**Expected Behavior**
According to the OpenID Connect specifications, the ID Token can optionally contain an `at_hash` claim, that's calculated from a hash of the Access Token.

**Current Behavior**
The provider for the token endpoint included in the library (`OAuth2AuthorizationCodeAuthenticationProvider`) actually generates the Access Token before the ID Token, but the generated Access Token is not included in the `OAuth2TokenContext` argument that's passed to the ID Token generator. So, there's no way to include the `at_hash` claim if using the given provider.

**Context**
The standard OpenID Connect claims should be supported out of the box, so it should be possible to add the `at_hash` claim, at least by implementing an `OAuth2TokenCustomizer`.

**Comment by jgrandja** [comment]
@pixel13 Thanks for reporting this. You are right:

> the generated Access Token is not included in the `OAuth2TokenContext` argument that's passed to the ID Token generator

We will look at enhancing this soon.

**Comment by jgrandja** [comment]
@pixel13 The access token is now accessible as follows:

```java
@Bean
OAuth2TokenCustomizer<JwtEncodingContext> jwtCustomizer() {
	return context -> {
		if (context.getTokenType().getValue().equals(OidcParameterNames.ID_TOKEN)) {
			OAuth2AccessToken accessToken = context.getAuthorization().getAccessToken().getToken();

			// TODO Calculate at_hash claim

		}
	};
}
```

**Comment by dlehammer** [comment]
Hi @jgrandja,

Apologies in advance as I'm probably holding it wrong, but I seem unable to locate `at_hash` claim support in the Spring authorization-server v1 similar to ex. [org.mitre.openid.connect.util.IdTokenHashUtils.java](https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/blob/d074573de0c8b8e339add89a17a2bd000a1c6378/openid-connect-server/src/main/java/org/mitre/openid/connect/util/IdTokenHashUtils.java).
Ie. since the `at_hash` claim is [REQUIRED](https://openid.net/specs/openid-connect-implicit-1_0.html#IDToken) for some OIDC flows I would assume the support is present in-order to be compliant?

Looking forward to your insights :nerd_face:

**Comment by jgrandja** [comment]
@dlehammer The `at_hash` claim is REQUIRED for [Implicit Flow](https://openid.net/specs/openid-connect-core-1_0.html#ImplicitFlowAuth):

> REQUIRED. Access Token hash value. **If the ID Token is issued with an access_token in an Implicit Flow, this is REQUIRED**, which is the case for this subset of OpenID Connect.

There is no support for Implicit Flow. The current support is [Auth Code Flow](https://openid.net/specs/openid-connect-core-1_0.html#CodeFlowAuth) only.
