### ISSUE TITLE
Support for POST Authentication Requests

### ISSUE THREAD

**Issue by pixel13** [spring-projects/spring-authorization-server#745]
**Expected Behavior**
According to the OpenID Connect specifications, the Authentication Request can be sent using `GET` or `POST` method. Since the library implements OpenID Connect, it should work with both methods.

**Current Behavior**
The `OAuth2AuthorizationEndpointFilter` actually accept Authentication Requests sent by `POST`, but if the user is not already logged in, the server redirects to the login page, saving the original request in session by using the `HttpSessionRequestCache` class. Unfortunately, this class accept by default only `GET` requests: it could anyway be customized, but in this case there's no way to recover the flow after a successful login, since the invoked `SavedRequestAwareAuthenticationSuccessHandler` doesn't take into consideration that the original request can be sent by `POST` (it actually looks for a redirect URI with a query string, that's empty in a `POST` request).

**Context**
Since sending the Authentication Request by `POST` is a possibility that's included in the standard protocol, the library should support it out of the box.

**Comment by sjohnr** [comment]
Hi @pixel13, thanks for reaching out!

I find it interesting that the spec does allow a POST to the authorization endpoint but leaves details like establishing an authenticated session up to the implementation. However, replaying a saved POST request does not appear to be a best practice. According to [this comment](https://github.com/spring-projects/spring-security/issues/4188#issuecomment-270971034), one such concern with replayed POST requests is CSRF protection. In this case, CSRF is not required for the `GET /oauth2/authorize` endpoint because OAuth2 has a set of well-defined security considerations and recommendations (see [OAuth 2.0 Security Best Current Practice](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-security-topics-18) and [OAuth 2.0 Threat Model and Security Considerations](https://datatracker.ietf.org/doc/html/rfc6819)). However, the OpenID Connect 1.0 spec does state that CSRF protection be employed:

> When interacting with the End-User, the Authorization Server MUST employ appropriate measures against Cross-Site Request Forgery and Clickjacking as, described in Sections 10.12 and 10.13 of [OAuth 2.0](https://openid.net/specs/openid-connect-core-1_0.html#RFC6749) [RFC6749].

I would think this applies when using a `POST` and it should be up to the developer in consultation with the security team to open the authorization server up in this way, in which case we should not provide this behavior out of the box. As you mentioned, it can be customized with the `HttpSessionRequestCache.setRequestMatcher()`.

I could be wrong though. Do you find anything I've missed in the best practices documents or the OIDC spec that deals with this issue (replaying `POST` requests after authentication) specifically?

**Comment by pixel13** [comment]
Hi @sjohnr, 

I agree with you about all the security issues that must be taken into consideration when opening the authorization endpoint to `POST` requests. Generally speaking, I'd expect that an OIDC library should implement out of the box all the flows and variations included in the specifications, but I understand that there could be security issues that must be faced in different ways depending on the environment. 

Unfortunately, developing a custom solution to handle `POST` requests is not so simple, also because most of the involved classes of Spring Security are final, so they cannot be extended and must be rewritten from scratch. In my case, since I'm forced to expose also the `POST` for the authentication requests, I ended up using another solution to handle OIDC.

I see your point, anyway. Thanks for your answer.

**Comment by sjohnr** [comment]
Thanks for your reply @pixel13.

> Unfortunately, developing a custom solution to handle POST requests is not so simple, also because most of the involved classes of Spring Security are final

Do you have a specific example that I could look at? Is it mostly Spring Security-related classes you're referring to in this case? I also wonder if composition can help work around the `final` classes and avoid duplicating code.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.
