### ISSUE TITLE
how to update scope in /oauth2/token response (not scope claim in access_token)

### ISSUE THREAD

**Issue by lys2356** [spring-projects/spring-authorization-server#795]
**Expected Behavior**
Is there any way to update scope in token response, as addition to match scope in access_token

**Current Behavior**
scope in response of /oauth2/token is not updated by OAuth2TokenGenerator.
so, scope in /oauth2/token response will be different with scope in access_token after decryption

### for example: 
scope in response of /oauth2/token, which is matched request scope of /oauth2/authorize:
```json
{
    "access_token": "eyJraWQiOiI2NjRiMDU1ZS1mOTZkLTR",
    "refresh_token": "J4GNd_9DbA6ku8tmPCbgSIJ2pWlHSjK",
    "scope": "openid model:read model:write flow:read flow:write",
    "token_type": "Bearer",
    "expires_in": 86399
}
```
but, scope in access_token is updated by OAuth2TokenGenerator:
```json
{
    "sub": "1000100000001",
    "aud": "titan",
    "nbf": 1656561423,
    "scope": [
        "openid",
        "model:read"
    ],
    "iss": "http://192.168.129.206:30184",
    "exp": 1656647823,
    "iat": 1656561423,
    "tenant": "1000100000001"
}
```

**Context**

**we has the same use case as discussed in issue #147.**

I want to use GrantAuthorities in UserDetails to limit scopes in /oauth2/token response. 
but OAuth2TokenCustomizer/OAuth2TokenGenerator can only be used to update scope claim in access_token.

After reading the code in [OAuth2AuthorizationCodeAuthenticationProvider.java](https://github.com/spring-projects/spring-authorization-server/blob/3f5e7c793bbc9875d2753fb5427423d553dd9b16/oauth2-authorization-server/src/main/java/org/springframework/security/oauth2/server/authorization/authentication/OAuth2AuthorizationCodeAuthenticationProvider.java#L132)

as I known the scope in token response is hardcoded to `authorization.getAttribute(OAuth2Authorization.AUTHORIZED_SCOPE_ATTRIBUTE_NAME)` as code below.
**How can I update this value? Or Other Method to update SCOPE in /oauth2/token**

```java
		// @formatter:off
		DefaultOAuth2TokenContext.Builder tokenContextBuilder = DefaultOAuth2TokenContext.builder()
				.registeredClient(registeredClient)
				.principal(authorization.getAttribute(Principal.class.getName()))
				.providerContext(ProviderContextHolder.getProviderContext())
				.authorization(authorization)
				.authorizedScopes(authorization.getAttribute(OAuth2Authorization.AUTHORIZED_SCOPE_ATTRIBUTE_NAME))
				.authorizationGrantType(AuthorizationGrantType.AUTHORIZATION_CODE)
				.authorizationGrant(authorizationCodeAuthentication);
		// @formatter:on


		OAuth2Authorization.Builder authorizationBuilder = OAuth2Authorization.from(authorization);


		// ----- Access token -----
		OAuth2TokenContext tokenContext = tokenContextBuilder.tokenType(OAuth2TokenType.ACCESS_TOKEN).build();
		OAuth2Token generatedAccessToken = this.tokenGenerator.generate(tokenContext);
		if (generatedAccessToken == null) {
			OAuth2Error error = new OAuth2Error(OAuth2ErrorCodes.SERVER_ERROR,
					"The token generator failed to generate the access token.", ERROR_URI);
			throw new OAuth2AuthenticationException(error);
		}
		OAuth2AccessToken accessToken = new OAuth2AccessToken(OAuth2AccessToken.TokenType.BEARER,
				generatedAccessToken.getTokenValue(), generatedAccessToken.getIssuedAt(),
				generatedAccessToken.getExpiresAt(), tokenContext.getAuthorizedScopes());
		if (generatedAccessToken instanceof ClaimAccessor) {
			authorizationBuilder.token(accessToken, (metadata) ->
					metadata.put(OAuth2Authorization.Token.CLAIMS_METADATA_NAME, ((ClaimAccessor) generatedAccessToken).getClaims()));
		} else {
			authorizationBuilder.accessToken(accessToken);
		}
```

**Comment by sjohnr** [comment]
@lys2356, thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/questions/tagged/spring-security). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces this issue if you feel this is a genuine bug. If you feel there is an enhancement here instead of a question, please update the details to be more specific to the enhancement request and I'll be happy to re-open if necessary.

Having said that, please note that you can already customize the token response. See [OAuth2 Token Endpoint](https://docs.spring.io/spring-authorization-server/docs/current/reference/html/protocol-endpoints.html#oauth2-token-endpoint) in the docs for more on customizing.
