### ISSUE TITLE
How to set the access_token to keep inventory for a period of time after being refreshed?

### ISSUE THREAD

**Issue by itunic** [spring-projects/spring-authorization-server#803]
How to set the access_token to keep inventory for a period of time after being refreshed?
In this way, the user does not need to care about the problem that the access_token is refreshed and the request fails when concurrency occurs!

**Comment by sjohnr** [comment]
@itunic, thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/questions/tagged/spring-security). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces this issue if you feel this is a genuine bug.
