### ISSUE TITLE
Cannot get token from /oauth2/token 

### ISSUE THREAD

**Issue by ls-alberto-pellizzon** [spring-projects/spring-authorization-server#805]
It seems like I cannot get any token from the /oauth2/token endpoint
My security config

```java
public class AuthorizationServerSecurityConfig extends WebSecurityConfigurerAdapter {   
    @Override
    public void configure(HttpSecurity http) throws Exception {
        OAuth2AuthorizationServerConfigurer<HttpSecurity> authorizationServerConfigurer = new OAuth2AuthorizationServerConfigurer();
        var endpointsMatcher = authorizationServerConfigurer.getEndpointsMatcher();
        http.requestMatcher(endpointsMatcher).authorizeRequests((authorizeRequests) -> {
            ((AuthorizedUrl)authorizeRequests.anyRequest()).authenticated();
        }).csrf((csrf) -> {
            csrf.ignoringRequestMatchers(new RequestMatcher[]{endpointsMatcher});
        }).apply(authorizationServerConfigurer);
        authorizationServerConfigurer.registeredClientRepository(registeredClientRepository());
    }

    @Bean
    public ProviderSettings providerSettings() {
        return ProviderSettings.builder().build();
    }

    @Bean
    public RegisteredClientRepository registeredClientRepository() {
        var registeredClient = RegisteredClient.withId(UUID.randomUUID().toString())
            .clientId("articles-client")
            .clientSecret("{noop}secret")
            .clientAuthenticationMethod(ClientAuthenticationMethod.CLIENT_SECRET_POST)
            .authorizationGrantType(AuthorizationGrantType.CLIENT_CREDENTIALS)
            .build();
        return new InMemoryRegisteredClientRepository(registeredClient);
    }
}
```

I tried with just `OAuth2AuthorizationServerConfiguration.applyDefaultSecurity(http)` but it will not add any client repository

Curl request:
```bash
curl --request POST \
  --url http://localhost:4000/oauth2/token \
  --header 'Authorization: Basic YXJ0aWNsZXMtY2xpZW50Ontub29wfXNlY3JldA==' \
  --header 'Content-Type: application/x-www-form-urlencoded' \
  --data grant_type=client_credentials \
  --data client_id=articles-client \
  --data 'client_secret={noop}secret'
```
Response
```
{
	"error": "invalid_client"
}
```

Digging down I found that this method OAuth2ClientCredentialsAuthenticationProvider::supports

```java
public boolean supports(Class<?> authentication) {
    return OAuth2ClientCredentialsAuthenticationToken.class.isAssignableFrom(authentication);
  }
```

Is returning false for my request.
Lib version: 0.3.1

**Comment by sjohnr** [comment]
@ls-alberto-pellizzon, thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/questions/tagged/spring-security). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces this issue if you feel this is a genuine bug.

One thing that may be helpful is that the "{noop}secret" is not the secret, only the encoded secret stored in the in-memory repository. The secret is just "secret", e.g. `--data 'client_secret=secret'`. Please try that and if you still have issues, open a stackoverflow question and I'll take a look.
