### ISSUE TITLE
Support for custom state generator

### ISSUE THREAD

**Issue by chenzhenjia** [spring-projects/spring-authorization-server#828]
`org.springframework.security.oauth2.server.authorization.authentication.OAuth2AuthorizationCodeRequestAuthenticationProvider#DEFAULT_STATE_GENERATOR`  Is it a static final field, can it support setting the generator through the setter method?

**Comment by jgrandja** [comment]
@chenzhenjia Why do you need the ability to set a custom `state` generator? Can you provide more details for your use case?

**Comment by chenzhenjia** [comment]
I want to use hashids with long to speed up the OAuth2Authorization query, so I need to customize the stateGenerator

**Comment by jgrandja** [comment]
@chenzhenjia 

> to speed up the OAuth2Authorization query

I'm curious, how do you find it slow? Can you provide more details on the metrics recorded?

**Comment by chenzhenjia** [comment]
According to my understanding, string query is slower in mysql compared to bigint type. If I add an index, bigint will be faster than blob or varchar

**Comment by jgrandja** [comment]
@chenzhenjia The `OAuth2AuthorizationService.findByToken(String token, @Nullable OAuth2TokenType tokenType)` receives a token of type `String`, so even if you can customize the `state` token type to a `number`, it still would need to be passed in as a `String` given the interface.

> Can you provide more details on the metrics recorded so I can understand the performance issue?

I'm not sure there is much of a performance hit to warrant exposing a new public API to allow the state to be customized. Please keep in mind that we limit the APIs we expose publicly because it limits us from making changes in a passive way and it also increases our maintenance of the public APIs. We will only expose a public API if it makes sense and if we feel it will be widely used. I don't think it makes sense for this case.

> I want to use hashids with long to speed up the OAuth2Authorization query, so I need to customize the stateGenerator

Instead of providing a `setStateGenerator()` you can supply your own `OAuth2AuthorizationService` that simply translates the incoming `String` `token` to a `number` using `token.hashCode()`. You would first need to `save()` the token using `token.hashCode()` and then the subsequent `findByToken()` can translate to `token.hashCode()` and then perform the query search.

I'm going to close this as the solution provided will work for your use case.

**Comment by prettykingking** [comment]
@jgrandja I think he didn't elaborate exactly what he want with a customizable state generator. He @chenzhenjia want more control of generated state string, i.e. length, characters, as query performance is not the only issue he may come up against. The present fixed default state generator generate 96 random long string, that is too long for general purpose. Characters and length of the state string should be application specific.

I hope i elaborated the issue well.

**Comment by jamakal** [comment]
Would also love to see this change. The state token is inconsistent with access/refresh tokens in that a custom generator cannot be easily provided.

My implementation of multi-tenancy has separate schemas per tenant and relies on embedding a tenant identifier in tokens to indicate which datastore the token should be looked up in as trying each one is too expensive. This is easy with other tokens, however state tokens are the exception to this.

I've worked around this with a custom AuthenticationProvider that delegates to the default and then modifies the generated token, but it's clunky and inconsistent.
