### ISSUE TITLE
Any possible to expose those default endpoint in swagger page

### ISSUE THREAD

**Issue by doctormacky** [spring-projects/spring-authorization-server#848]
**Expected Behavior**

There are so many default endpoints such as /oauth2/token, /oauth/introspect endpoints, any possible that those endpoints be exposed to swagger ui when integrated with [springdoc](https://springdoc.org) 

**Current Behavior**

Can not show those default endpoints in springdoc

**Context**

**Comment by jgrandja** [comment]
@doctormacky It looks like springdoc introspects `@Controller` and `@RestController` to automatically generate API docs.

The Spring Authorization Server endpoints are implemented as `Filter`'s so the integration is not compatible with springdoc.

As well, swagger is typically used to expose API's that provide services at the application level. The OAuth2 endpoints are not considered "business" API's so it doesn't really fit the use case. And personally, I wouldn't publish security-related endpoints and it's details as this really should be kept confidential.

Either way, integration with springdoc would not be a feature implemented by this framework since that would not be OAuth2 or application security related, which is the sole focus of this framework.
