### ISSUE TITLE
Multiple access tokens for user/client combination in DB

### ISSUE THREAD

**Issue by dciarniello** [spring-projects/spring-authorization-server#873]
**Describe the bug**
Repeated use of the authorization code grant flow for a given user/client combination results in multiple records in the database when using **JdbcOAuth2AuthorizationService**.  That could quickly fill up the DB with unnecessary records.

**To Reproduce**
Configure the authorization server to use the **JdbcOAuth2AuthorizationService** and repeatedly go through the authorization code grant flow for a given user/client combination.

**Expected behavior**
A pre-existing access token is either deleted or updated when issuing a new access token to a client for a given user.

**Comment by jgrandja** [comment]
@dciarniello 

> Repeated use of the authorization code grant flow for a given user/client combination results in multiple records in the database when using `JdbcOAuth2AuthorizationService`

This is the expected behaviour. Each time a client goes through an authorization grant flow, a new access token is generated and associated to a new `OAuth2Authorization` and saved via `OAuth2AuthorizationService`. **NOTE:** A new `OAuth2Authorization` must be created for each instance of an authorization grant flow completed.

Please review the spec to understand the [authorization_code](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-v2-1-05#section-4.1) grant flow.

In a typical client flow, the client will go through an authorization grant flow to obtain the token. It will use the token to call protected resources. When the client no longer needs the access token it can call the [Token Revocation endpoint](https://docs.spring.io/spring-authorization-server/docs/current/reference/html/protocol-endpoints.html#oauth2-token-revocation-endpoint) to revoke the token.

> A pre-existing access token is either deleted or updated when issuing a new access token to a client for a given user.

This is non-standard behaviour and would have auditing implications. If you require the token to be deleted when revoked then you will need to provide a custom `OAuth2AuthorizationService` to delete the access token and/or `OAuth2Authorization`. The default behaviour simply invalidates the access token but it is kept in the backing store.

Closing this as invalid as the current design and implementation is to spec.

**Comment by dciarniello** [comment]
I may be missing something but I don't see anywhere in the spec reference to auditing or handling of pre-existing access tokens so while updating might be against spec, I don't see that deleting is.

I do understand where you're coming from but the reality is that the current implementation is likely to overload a database.

**Comment by carloterzo** [comment]
@jgrandja what do you mean as: "A new OAuth2Authorization must be created for each instance of an authorization grant flow completed." 
You mean "instance" as cookie based session that start after a successful username/password authentication ?

**Comment by jgrandja** [comment]
@carloterzo Please see the [reference documentation](https://docs.spring.io/spring-authorization-server/docs/current/reference/html/) for details on [OAuth2Authorization](https://docs.spring.io/spring-authorization-server/docs/current/reference/html/core-model-components.html#oauth2-authorization).

I would also suggest reviewing the documentation links in [Getting Started](https://github.com/spring-projects/spring-authorization-server#getting-started).
