### ISSUE TITLE
How can I customize the oauth2loginauthenticationprovider class

### ISSUE THREAD

**Issue by shanzhaozhen** [spring-projects/spring-authorization-server#879]
How can I customize the oauth2loginauthenticationprovider class

Due to network fluctuations, we need to deal with timeout related issues.

However, the design has been fixed, and there is no way to customize it. It is not easy to extend the filter.

```(java)
// OAuth2loginauthenticationprovider.class

OAuth2AuthorizationCodeAuthenticationToken authorizationCodeAuthenticationToken;
try {
	authorizationCodeAuthenticationToken = (OAuth2AuthorizationCodeAuthenticationToken) this.authorizationCodeAuthenticationProvider
			.authenticate(new OAuth2AuthorizationCodeAuthenticationToken(
					loginAuthenticationToken.getClientRegistration(),
					loginAuthenticationToken.getAuthorizationExchange()));
}
catch (OAuth2AuthorizationException ex) {
	OAuth2Error oauth2Error = ex.getError();

	// todo: 处理超时问题

	throw new OAuth2AuthenticationException(oauth2Error, oauth2Error.toString(), ex);
}
```

**Comment by jgrandja** [comment]
@shanzhaozhen This issue should have been logged in [Spring Security](https://github.com/spring-projects/spring-security/issues) since `OAuth2LoginAuthenticationProvider` lives in the `oauth2-client` module.

However, this is a question, which is better suited to [Stack Overflow](https://stackoverflow.com/). We prefer to use GitHub issues only for bugs and enhancements.
