### ISSUE TITLE
Simultaneous access token requests result in authorizations having identical access tokens

### ISSUE THREAD

**Issue by jorisdejong85** [spring-projects/spring-authorization-server#913]
**Describe the bug**
I ran into an issue using the client credentials flow where the authorization server responds with multiple identical access tokens when executing token requests shortly after each other or simultaneously. The issue does not exist when there is a 1 second delay in between token requests. 

This issue is reproducible in an out-of-the-box spring-authorization-server. When using the default JDBC setup, introspecting one of the duplicate access tokens, results in JdbcOAuth2AuthorizationService picking the first (index 0) authorization result. When using JPA, an IncorrectResultSizeDataAccessException exception is thrown.

**To Reproduce**
1. Clone spring-authorization-server v0.3.1
2. Configure JPA using the [docs](https://docs.spring.io/spring-authorization-server/docs/current/reference/html/guides/how-to-jpa.html) 
3. Start server `./gradlew -b samples/default-authorizationserver/samples-default-authorizationserver.gradle bootRun`
4. Execute multiple access token requests simultaneously
5. Notice some or all responses containing identical access tokens
6. Execute an introspect request, using one of the duplicate access tokens
7. An exception is thrown "org.springframework.dao.IncorrectResultSizeDataAccessException: query did not return a unique result: 10"

**Expected behavior**
Subsequent access token requests always result in unique access tokens

**Sample**
I have created a sample containing an out-of-the-box spring-authorization-server v0.3.1 and JPA configured. There is also a test included that runs 10 requests **with** and **without** a 1 second delay.
[Reproducible sample](https://github.com/jorisdejong85/spring-authorization-server).
[Test cases](https://github.com/jorisdejong85/spring-authorization-server/blob/main/samples/default-authorizationserver/src/test/java/sample/DefaultAuthorizationServerJpaAccessTokenTests.java)

**Comment by jorisdejong85** [comment]
I took some time to dive in the code and pinpointed the issue to the "iat", "nbf", and "exp" claims working with seconds from epoch, which is by JWT design. This results in identical tokens for simultaneous requests in the same second. If it were milliseconds, it wouldn't really be a problem. I created a workaround by adding a randomly generated "jti" claim via the OAuth2TokenCustomizer.

**Comment by jgrandja** [comment]
@jorisdejong85 

> This issue is reproducible in an out-of-the-box spring-authorization-server

No it's not. The default `OAuth2AuthorizationService` is `InMemoryOAuth2AuthorizationService`, which behaves the same as `JdbcOAuth2AuthorizationService`, by picking the first `OAuth2Authorization`.

The sample you provided is customized with JPA so it doesn't qualify as a default configuration.

Regardless, in all 3 scenarios the expected `OAuth2Authorization` is either not returned or fails in the JPA case.

However, this test is not a valid real-world case scenario. When a client obtains a token, it will use it for some time or until it expires. A client would not continuously and simultaneously fetch a new access token and not use it. This may be a valid flow if you're performing a load test but then you'll need to ensure the access token generated is unique, e.g. by adding a `jti` claim.

I'm going to close this since this would not happen in a real world scenario.
