### ISSUE TITLE
HTTP Basic credentials Extraction

### ISSUE THREAD

**Issue by periplanomenos** [spring-projects/spring-authorization-server#985]
Description: 
ClientSecretBasicAuthenticationConverter class extracts HTTP Basic credentials from HTTP Header Authorization and URL decodes them after having decode authorization header from Base64. URL decoding is not necessary and causes problems with special characters (e.g. %). 

Description of the bug: 
ClientSecretBasicAuthenticationConverter class at extraction phase decodes authorization header from Base64 and then decodes decoded credentials from URL (using URL decoder). The second step is not necessary and causes problem with special characters (e.g. %). Spring security libraries do not URL decode client credentials that are being ectracted from HTTP Header Authorization. Spring security libraries only decode authorization header from Base64.

Reproduce:
Use for password at client credentials percent sign, e.g. password %5^gis%h@.

Expected behavior:
ClientSecretBasicAuthenticationConverter class should not URL decode decoded credentials. Following lines at the previous mentioned class should be either removed or enabled ad hoc (e.g. flag)

		try {
			clientID = URLDecoder.decode(credentials[0], StandardCharsets.UTF_8.name());
			clientSecret = URLDecoder.decode(credentials[1], StandardCharsets.UTF_8.name());
		} catch (Exception ex) {
			throw new OAuth2AuthenticationException(new OAuth2Error(OAuth2ErrorCodes.INVALID_REQUEST), ex);
		}

**Comment by jgrandja** [comment]
@periplanomenos Please review [Section 2.3.1](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-v2-1-07#section-2-3-1).  Client Password:

> Clients in possession of a client password MAY use the HTTP Basic
   authentication scheme as defined in [[RFC2617](https://datatracker.ietf.org/doc/html/rfc2617)] to authenticate with
   the authorization server.  **The client identifier is encoded using the
   "application/x-www-form-urlencoded" encoding algorithm per
   [Appendix B](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-v2-1-07#appendix-B), and the encoded value is used as the username; the client
   password is encoded using the same algorithm and used as the
   password.**  The authorization server MUST support the HTTP Basic
   authentication scheme for authenticating clients that were issued a
   client password.

I'll close this since the current implementation is implemented to spec.
