### ISSUE TITLE
v0.4.0 removes classes without stating breaking changes in release

### ISSUE THREAD

**Issue by bjornharvold** [spring-projects/spring-authorization-server#986]
**Describe the bug**
When upgrading from v0.3.1 to v0.4.0, packages classes such as 
- org.springframework.security.config.annotation.web.configurers.oauth2.server.authorization
- OAuth2AuthorizationServerConfiguration
- ProviderSettings
- OAuth2AuthorizationServerConfigurer

...have been removed without telling us how to migrate to the new way of doing things.

Stuck upgrading until we receive guidance.

Thank you

**Comment by ramonmalcolm10** [comment]
Version 1.0.0 is release, why not migrate to that version? The [documentation](https://docs.spring.io/spring-authorization-server/docs/current/reference/html/getting-started.html) can assist.

**Comment by bjornharvold** [comment]
Hi @ramonmalcolm10 

I do believe that entails upgrading the entire spring stack to v6 which we are not ready for yet.

**Comment by ramonmalcolm10** [comment]
Did you look at any of the sample project, they should be able to guide you. https://github.com/spring-projects/spring-authorization-server/tree/main/samples

**Comment by bjornharvold** [comment]
Most likely. Just submitted this because this was a release that did not contain the necessary information to do an easy upgrade. Minor releases should not contain breaking changes but I understand that SAS is not GA.

**Comment by sjohnr** [comment]
Hi @bjornharvold!

Sorry to hear you're having trouble. See the [releases](https://github.com/spring-projects/spring-authorization-server/releases) page, where there are a number of milestone releases ([0.4.0-M1](https://github.com/spring-projects/spring-authorization-server/releases/tag/0.4.0-M1), [0.4.0-M2](https://github.com/spring-projects/spring-authorization-server/releases/tag/0.4.0-M2), [0.4.0-RC1](https://github.com/spring-projects/spring-authorization-server/releases/tag/0.4.0-RC1)) in addition to [0.4.0](https://github.com/spring-projects/spring-authorization-server/releases/tag/0.4.0) which contain release notes for each release. Breaking changes are listed there with links to the issue where you can find the commit for each change.

At this time, there is not a migration guide, but starting with 1.0 the project will use the same approach as other Spring projects. If you have any specific questions, feel free to add a link to the stackoverflow question and I'll try and help you out as best I can. I will mention that the team will be out of the office quite a bit for the next month due to the holidays but we'll try and be available to help.

**Comment by bjornharvold** [comment]
Hi @sjohnr and thank you for all that information 🙇🏼‍♂️
