### ISSUE TITLE
Custom token store (for mongodb) - How to set it?

### ISSUE THREAD

**Issue by casper5822** [spring-projects/spring-authorization-server#988]
**Expected Behavior**

Just like the old webserverconfigureradapter, where i can set my custom tokenstore:

       @Autowired
	private OAuth2TokenStore tokenStore;

       @Override
	public void configure(AuthorizationServerEndpointsConfigurer endpoints) throws Exception {
        
		endpoints.tokenStore(tokenStore)
				 .authenticationManager(authenticationManager)
				 .userDetailsService(userDetailsService)
				 .tokenServices(tokenServices());
	}

**Current Behavior**

It's not clear how i can create and set a custom token store in the new configuration that uses my mongodb collections for oauth2AccessToken and oauth2RefreshToken.

**Context**

We cannot migrate the entire platform from spring boot 2.5.7 to spring boot 3.0.0 because of the change in spring security authorization server.

**Comment by publicocean0** [comment]
what i understood (i hope correctly)  is that : 
The tokens dont use anymore a store for saving the tokens  but are saved internally at authorization table  in a hashmap. 
Using mongodb it is a bit complex to handle this schema , above all when you use generic map containing generic objects.

**Comment by casper5822** [comment]
@publicocean0  yes exactly. With the previous webconfigurationadapter we implemented our token store to handle the storage on our mongodb database. So we created two repositories to handle findByTokenId, saveToken and the other interface methods. So my question is if is there a similar way to pass our token store (we can implement new logic if it is the case) in order to use our authorization logic. I read something abount Oauth2AuthorizationService in the docs but it's not clear how ti implement a custom logic. On the other hand there is an example for UserCustomerDetailService. 

So how can we full migrate from spring security oauth2 webconfingureradapter ?

**Comment by sjohnr** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/questions/tagged/spring-security). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces this issue if you feel this is a genuine bug.

Having said that, you may find the [how-to guide on using JPA](https://docs.spring.io/spring-authorization-server/docs/current/reference/html/guides/how-to-jpa.html) valuable.

**Comment by arianox** [comment]
@casper5822 Did you find a solution to the problem?
