### ISSUE TITLE
How to custom a grant type 

### ISSUE THREAD

**Issue by pigping88** [spring-projects/spring-authorization-server#994]
Now, i need another grant type (such as: wechat or mobile). How to custom a grant type?

**Comment by sjohnr** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/questions/tagged/spring-security). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces this issue if you feel this is a genuine bug.
