### ISSUE TITLE
add audience field on RegisteredClient Entity

### ISSUE THREAD

**Issue by barneag** [spring-projects/spring-authorization-server#997]
Hey, 
As part of **private_key_jwt** flow, We want to generate JWT with **audience** of the registered client.
Currently by default - the framework puts clientId there.

**Comment by sjohnr** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/questions/tagged/spring-security). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces this issue if you feel this is a genuine bug.

Having said that, you may find the section of the reference guide on [OAuth2TokenCustomizer](https://docs.spring.io/spring-authorization-server/docs/current/reference/html/core-model-components.html#oauth2-token-customizer) valuable.

**Comment by barneag** [comment]
Hey @sjohnr 
I know the customizer, but my question is:
Why we have set of **scopes** on the registeredClient, and not also set of **audience**?
