### ISSUE TITLE
How to replace OAuth2AuthorizationEndpointFilter

### ISSUE THREAD

**Issue by csxcsx00** [spring-projects/spring-authorization-server#998]
**Expected Behavior**

I want to replace OAuth2AuthorizationEndpointFilter with my own implemention, but it seemed not supported currently.
The following usage is expected:
`http.addFilterAt(new MyOAuth2AuthorizationEndpointFilter(), OAuth2AuthorizationEndpointFilter.class);`

**Current Behavior**

I want to send json response to client in OAuth2AuthorizationEndpointFilter and do redirect with client, rather than do redirect with server.

**Context**

**Comment by jgrandja** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces this issue if you feel this is a genuine bug.

> I want to send json response to client in OAuth2AuthorizationEndpointFilter

See the reference documentation for `OAuth2AuthorizationEndpointFilter` as it describes how you can [override the Authorization Response](https://docs.spring.io/spring-authorization-server/docs/current/reference/html/protocol-endpoints.html#oauth2-authorization-endpoint) by supplying an `AuthenticationSuccessHandler` via `OAuth2AuthorizationServerConfigurer. authorizationEndpoint().authorizationResponseHandler()`.
